import type { Problem } from '../../types/content.ts';
import { leetCodeUrl } from '../../types/content.ts';

/** Array problems (1-D scans, transforms, and grids). */
export const arrayProblems: Problem[] = [
  // ----- Easy -----
  {
    id: '1',
    title: 'Two Sum',
    slug: 'two-sum',
    leetcodeUrl: leetCodeUrl('two-sum'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['hash-map-complement'],
  },
  {
    id: '217',
    title: 'Contains Duplicate',
    slug: 'contains-duplicate',
    leetcodeUrl: leetCodeUrl('contains-duplicate'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['seen-set'],
  },
  {
    id: '121',
    title: 'Best Time to Buy and Sell Stock',
    slug: 'best-time-to-buy-and-sell-stock',
    leetcodeUrl: leetCodeUrl('best-time-to-buy-and-sell-stock'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['track-minimum'],
  },
  {
    id: '88',
    title: 'Merge Sorted Array',
    slug: 'merge-sorted-array',
    leetcodeUrl: leetCodeUrl('merge-sorted-array'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['merge-from-end'],
  },
  {
    id: '283',
    title: 'Move Zeroes',
    slug: 'move-zeroes',
    leetcodeUrl: leetCodeUrl('move-zeroes'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['two-pointers-compact'],
  },
  {
    id: '26',
    title: 'Remove Duplicates from Sorted Array',
    slug: 'remove-duplicates-from-sorted-array',
    leetcodeUrl: leetCodeUrl('remove-duplicates-from-sorted-array'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['slow-fast-write'],
  },
  {
    id: '27',
    title: 'Remove Element',
    slug: 'remove-element',
    leetcodeUrl: leetCodeUrl('remove-element'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['slow-fast-write'],
  },
  {
    id: '169',
    title: 'Majority Element',
    slug: 'majority-element',
    leetcodeUrl: leetCodeUrl('majority-element'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['boyer-moore-vote'],
  },
  {
    id: '66',
    title: 'Plus One',
    slug: 'plus-one',
    leetcodeUrl: leetCodeUrl('plus-one'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['carry-propagation'],
  },
  {
    id: '268',
    title: 'Missing Number',
    slug: 'missing-number',
    leetcodeUrl: leetCodeUrl('missing-number'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['xor-cancel'],
  },
  {
    id: '136',
    title: 'Single Number',
    slug: 'single-number',
    leetcodeUrl: leetCodeUrl('single-number'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['xor-cancel'],
  },
  {
    id: '724',
    title: 'Find Pivot Index',
    slug: 'find-pivot-index',
    leetcodeUrl: leetCodeUrl('find-pivot-index'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['prefix-sums'],
  },
  {
    id: '977',
    title: 'Squares of a Sorted Array',
    slug: 'squares-of-a-sorted-array',
    leetcodeUrl: leetCodeUrl('squares-of-a-sorted-array'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['two-pointers-fill'],
  },
  {
    id: '35',
    title: 'Search Insert Position',
    slug: 'search-insert-position',
    leetcodeUrl: leetCodeUrl('search-insert-position'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['binary-search-bounds'],
  },
  {
    id: '118',
    title: "Pascal's Triangle",
    slug: 'pascals-triangle',
    leetcodeUrl: leetCodeUrl('pascals-triangle'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['build-rows'],
  },
  {
    id: '119',
    title: "Pascal's Triangle II",
    slug: 'pascals-triangle-ii',
    leetcodeUrl: leetCodeUrl('pascals-triangle-ii'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['rolling-row'],
  },
  {
    id: '189',
    title: 'Rotate Array',
    slug: 'rotate-array',
    leetcodeUrl: leetCodeUrl('rotate-array'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['reverse-three-times'],
  },
  {
    id: '219',
    title: 'Contains Duplicate II',
    slug: 'contains-duplicate-ii',
    leetcodeUrl: leetCodeUrl('contains-duplicate-ii'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['sliding-window-set'],
  },
  {
    id: '349',
    title: 'Intersection of Two Arrays',
    slug: 'intersection-of-two-arrays',
    leetcodeUrl: leetCodeUrl('intersection-of-two-arrays'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['set-intersection'],
  },
  {
    id: '350',
    title: 'Intersection of Two Arrays II',
    slug: 'intersection-of-two-arrays-ii',
    leetcodeUrl: leetCodeUrl('intersection-of-two-arrays-ii'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['frequency-intersection'],
  },
  {
    id: '448',
    title: 'Find All Numbers Disappeared in an Array',
    slug: 'find-all-numbers-disappeared-in-an-array',
    leetcodeUrl: leetCodeUrl('find-all-numbers-disappeared-in-an-array'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['index-marking'],
  },
  {
    id: '414',
    title: 'Third Maximum Number',
    slug: 'third-maximum-number',
    leetcodeUrl: leetCodeUrl('third-maximum-number'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['track-top-k'],
  },
  {
    id: '697',
    title: 'Degree of an Array',
    slug: 'degree-of-an-array',
    leetcodeUrl: leetCodeUrl('degree-of-an-array'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['first-last-positions'],
  },
  {
    id: '1122',
    title: 'Relative Sort Array',
    slug: 'relative-sort-array',
    leetcodeUrl: leetCodeUrl('relative-sort-array'),
    difficulty: 'Easy',
    dataStructures: ['array', 'sorting'],
    patterns: ['counting-order'],
  },
  {
    id: '905',
    title: 'Sort Array By Parity',
    slug: 'sort-array-by-parity',
    leetcodeUrl: leetCodeUrl('sort-array-by-parity'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['two-pointers-partition'],
  },
  {
    id: '922',
    title: 'Sort Array By Parity II',
    slug: 'sort-array-by-parity-ii',
    leetcodeUrl: leetCodeUrl('sort-array-by-parity-ii'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['two-pointers-fill'],
  },
  {
    id: '1491',
    title: 'Average Salary Excluding the Minimum and Maximum Salary',
    slug: 'average-salary-excluding-the-minimum-and-maximum-salary',
    leetcodeUrl: leetCodeUrl('average-salary-excluding-the-minimum-and-maximum-salary'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['single-scan'],
  },
  {
    id: '1351',
    title: 'Count Negative Numbers in a Sorted Matrix',
    slug: 'count-negative-numbers-in-a-sorted-matrix',
    leetcodeUrl: leetCodeUrl('count-negative-numbers-in-a-sorted-matrix'),
    difficulty: 'Easy',
    dataStructures: ['matrix'],
    patterns: ['staircase-count'],
  },
  {
    id: '495',
    title: 'Teemo Attacking',
    slug: 'teemo-attacking',
    leetcodeUrl: leetCodeUrl('teemo-attacking'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['merge-overlaps-scan'],
  },
  {
    id: '228',
    title: 'Summary Ranges',
    slug: 'summary-ranges',
    leetcodeUrl: leetCodeUrl('summary-ranges'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['run-encoding'],
  },
  {
    id: '605',
    title: 'Can Place Flowers',
    slug: 'can-place-flowers',
    leetcodeUrl: leetCodeUrl('can-place-flowers'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['greedy-planting'],
  },
  {
    id: '643',
    title: 'Maximum Average Subarray I',
    slug: 'maximum-average-subarray-i',
    leetcodeUrl: leetCodeUrl('maximum-average-subarray-i'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['fixed-sliding-window'],
  },
  {
    id: '1480',
    title: 'Running Sum of 1d Array',
    slug: 'running-sum-of-1d-array',
    leetcodeUrl: leetCodeUrl('running-sum-of-1d-array'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['prefix-sums'],
  },
  {
    id: '1470',
    title: 'Shuffle the Array',
    slug: 'shuffle-the-array',
    leetcodeUrl: leetCodeUrl('shuffle-the-array'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['interleave-halves'],
  },
  {
    id: '1431',
    title: 'Kids With the Greatest Number of Candies',
    slug: 'kids-with-the-greatest-number-of-candies',
    leetcodeUrl: leetCodeUrl('kids-with-the-greatest-number-of-candies'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['max-baseline'],
  },
  {
    id: '1672',
    title: 'Richest Customer Wealth',
    slug: 'richest-customer-wealth',
    leetcodeUrl: leetCodeUrl('richest-customer-wealth'),
    difficulty: 'Easy',
    dataStructures: ['matrix'],
    patterns: ['row-sums'],
  },
  {
    id: '1512',
    title: 'Number of Good Pairs',
    slug: 'number-of-good-pairs',
    leetcodeUrl: leetCodeUrl('number-of-good-pairs'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['frequency-pairs'],
  },
  {
    id: '1365',
    title: 'How Many Numbers Are Smaller Than the Current Number',
    slug: 'how-many-numbers-are-smaller-than-the-current-number',
    leetcodeUrl: leetCodeUrl('how-many-numbers-are-smaller-than-the-current-number'),
    difficulty: 'Easy',
    dataStructures: ['array', 'sorting'],
    patterns: ['sorted-ranks'],
  },
  {
    id: '1389',
    title: 'Create Target Array in the Given Order',
    slug: 'create-target-array-in-the-given-order',
    leetcodeUrl: leetCodeUrl('create-target-array-in-the-given-order'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['insert-shift'],
  },
  {
    id: '1313',
    title: 'Decompress Run-Length Encoded List',
    slug: 'decompress-run-length-encoded-list',
    leetcodeUrl: leetCodeUrl('decompress-run-length-encoded-list'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['run-expansion'],
  },
  {
    id: '1773',
    title: 'Count Items Matching a Rule',
    slug: 'count-items-matching-a-rule',
    leetcodeUrl: leetCodeUrl('count-items-matching-a-rule'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['column-match'],
  },
  {
    id: '1588',
    title: 'Sum of All Odd Length Subarrays',
    slug: 'sum-of-all-odd-length-subarrays',
    leetcodeUrl: leetCodeUrl('sum-of-all-odd-length-subarrays'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['contribution-counting'],
  },
  {
    id: '1732',
    title: 'Find the Highest Altitude',
    slug: 'find-the-highest-altitude',
    leetcodeUrl: leetCodeUrl('find-the-highest-altitude'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['prefix-maximum'],
  },
  {
    id: '1380',
    title: 'Lucky Numbers in a Matrix',
    slug: 'lucky-numbers-in-a-matrix',
    leetcodeUrl: leetCodeUrl('lucky-numbers-in-a-matrix'),
    difficulty: 'Easy',
    dataStructures: ['matrix'],
    patterns: ['row-min-col-max'],
  },
  {
    id: '1252',
    title: 'Cells with Odd Values in a Matrix',
    slug: 'cells-with-odd-values-in-a-matrix',
    leetcodeUrl: leetCodeUrl('cells-with-odd-values-in-a-matrix'),
    difficulty: 'Easy',
    dataStructures: ['matrix'],
    patterns: ['parity-counts'],
  },
  {
    id: '1346',
    title: 'Check If N and Its Double Exist',
    slug: 'check-if-n-and-its-double-exist',
    leetcodeUrl: leetCodeUrl('check-if-n-and-its-double-exist'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['seen-set'],
  },
  {
    id: '941',
    title: 'Valid Mountain Array',
    slug: 'valid-mountain-array',
    leetcodeUrl: leetCodeUrl('valid-mountain-array'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['climb-then-descend'],
  },
  {
    id: '942',
    title: 'DI String Match',
    slug: 'di-string-match',
    leetcodeUrl: leetCodeUrl('di-string-match'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['low-high-pointers'],
  },
  {
    id: '888',
    title: 'Fair Candy Swap',
    slug: 'fair-candy-swap',
    leetcodeUrl: leetCodeUrl('fair-candy-swap'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['sum-difference-set'],
  },
  {
    id: '896',
    title: 'Monotonic Array',
    slug: 'monotonic-array',
    leetcodeUrl: leetCodeUrl('monotonic-array'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['direction-flags'],
  },
  {
    id: '830',
    title: 'Positions of Large Groups',
    slug: 'positions-of-large-groups',
    leetcodeUrl: leetCodeUrl('positions-of-large-groups'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['run-encoding'],
  },
  {
    id: '1089',
    title: 'Duplicate Zeros',
    slug: 'duplicate-zeros',
    leetcodeUrl: leetCodeUrl('duplicate-zeros'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['shift-from-end'],
  },
  {
    id: '1295',
    title: 'Find Numbers with Even Number of Digits',
    slug: 'find-numbers-with-even-number-of-digits',
    leetcodeUrl: leetCodeUrl('find-numbers-with-even-number-of-digits'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['digit-count'],
  },
  {
    id: '1299',
    title: 'Replace Elements with Greatest Element on Right Side',
    slug: 'replace-elements-with-greatest-element-on-right-side',
    leetcodeUrl: leetCodeUrl('replace-elements-with-greatest-element-on-right-side'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['suffix-maximum'],
  },
  {
    id: '1304',
    title: 'Find N Unique Integers Sum up to Zero',
    slug: 'find-n-unique-integers-sum-up-to-zero',
    leetcodeUrl: leetCodeUrl('find-n-unique-integers-sum-up-to-zero'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['symmetric-construction'],
  },
  {
    id: '1337',
    title: 'The K Weakest Rows in a Matrix',
    slug: 'the-k-weakest-rows-in-a-matrix',
    leetcodeUrl: leetCodeUrl('the-k-weakest-rows-in-a-matrix'),
    difficulty: 'Easy',
    dataStructures: ['matrix', 'heap'],
    patterns: ['row-strength-heap'],
  },
  {
    id: '1572',
    title: 'Matrix Diagonal Sum',
    slug: 'matrix-diagonal-sum',
    leetcodeUrl: leetCodeUrl('matrix-diagonal-sum'),
    difficulty: 'Easy',
    dataStructures: ['matrix'],
    patterns: ['diagonal-walk'],
  },
  {
    id: '566',
    title: 'Reshape the Matrix',
    slug: 'reshape-the-matrix',
    leetcodeUrl: leetCodeUrl('reshape-the-matrix'),
    difficulty: 'Easy',
    dataStructures: ['matrix'],
    patterns: ['flat-index-mapping'],
  },
  {
    id: '832',
    title: 'Flipping an Image',
    slug: 'flipping-an-image',
    leetcodeUrl: leetCodeUrl('flipping-an-image'),
    difficulty: 'Easy',
    dataStructures: ['matrix'],
    patterns: ['reverse-invert'],
  },
  {
    id: '867',
    title: 'Transpose Matrix',
    slug: 'transpose-matrix',
    leetcodeUrl: leetCodeUrl('transpose-matrix'),
    difficulty: 'Easy',
    dataStructures: ['matrix'],
    patterns: ['index-swap'],
  },
  {
    id: '766',
    title: 'Toeplitz Matrix',
    slug: 'toeplitz-matrix',
    leetcodeUrl: leetCodeUrl('toeplitz-matrix'),
    difficulty: 'Easy',
    dataStructures: ['matrix'],
    patterns: ['diagonal-invariant'],
  },
  {
    id: '661',
    title: 'Image Smoother',
    slug: 'image-smoother',
    leetcodeUrl: leetCodeUrl('image-smoother'),
    difficulty: 'Easy',
    dataStructures: ['matrix'],
    patterns: ['neighbor-average'],
  },
  {
    id: '1582',
    title: 'Special Positions in a Binary Matrix',
    slug: 'special-positions-in-a-binary-matrix',
    leetcodeUrl: leetCodeUrl('special-positions-in-a-binary-matrix'),
    difficulty: 'Easy',
    dataStructures: ['matrix'],
    patterns: ['row-col-counts'],
  },
  {
    id: '999',
    title: 'Available Captures for Rook',
    slug: 'available-captures-for-rook',
    leetcodeUrl: leetCodeUrl('available-captures-for-rook'),
    difficulty: 'Easy',
    dataStructures: ['matrix'],
    patterns: ['ray-scan'],
  },
  {
    id: '1716',
    title: 'Calculate Money in Leetcode Bank',
    slug: 'calculate-money-in-leetcode-bank',
    leetcodeUrl: leetCodeUrl('calculate-money-in-leetcode-bank'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['weekly-series'],
  },
  {
    id: '1752',
    title: 'Check if Array Is Sorted and Rotated',
    slug: 'check-if-array-is-sorted-and-rotated',
    leetcodeUrl: leetCodeUrl('check-if-array-is-sorted-and-rotated'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['drop-count'],
  },
  {
    id: '1800',
    title: 'Maximum Ascending Subarray Sum',
    slug: 'maximum-ascending-subarray-sum',
    leetcodeUrl: leetCodeUrl('maximum-ascending-subarray-sum'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['ascending-runs'],
  },
  {
    id: '1827',
    title: 'Minimum Operations to Make the Array Increasing',
    slug: 'minimum-operations-to-make-the-array-increasing',
    leetcodeUrl: leetCodeUrl('minimum-operations-to-make-the-array-increasing'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['greedy-raise'],
  },
  {
    id: '2011',
    title: 'Final Value of Variable After Performing Operations',
    slug: 'final-value-of-variable-after-performing-operations',
    leetcodeUrl: leetCodeUrl('final-value-of-variable-after-performing-operations'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['operation-fold'],
  },
  {
    id: '2037',
    title: 'Minimum Number of Moves to Seat Everyone',
    slug: 'minimum-number-of-moves-to-seat-everyone',
    leetcodeUrl: leetCodeUrl('minimum-number-of-moves-to-seat-everyone'),
    difficulty: 'Easy',
    dataStructures: ['array', 'sorting'],
    patterns: ['sort-then-match'],
  },
  {
    id: '2089',
    title: 'Find Target Indices After Sorting Array',
    slug: 'find-target-indices-after-sorting-array',
    leetcodeUrl: leetCodeUrl('find-target-indices-after-sorting-array'),
    difficulty: 'Easy',
    dataStructures: ['array', 'sorting'],
    patterns: ['sort-then-scan'],
  },
  {
    id: '2094',
    title: 'Finding 3-Digit Even Numbers',
    slug: 'finding-3-digit-even-numbers',
    leetcodeUrl: leetCodeUrl('finding-3-digit-even-numbers'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['digit-frequency'],
  },
  {
    id: '2144',
    title: 'Minimum Cost of Buying Candies With Discount',
    slug: 'minimum-cost-of-buying-candies-with-discount',
    leetcodeUrl: leetCodeUrl('minimum-cost-of-buying-candies-with-discount'),
    difficulty: 'Easy',
    dataStructures: ['array', 'sorting'],
    patterns: ['sort-descending-groups'],
  },
  {
    id: '2148',
    title: 'Count Elements With Strictly Smaller and Greater Elements',
    slug: 'count-elements-with-strictly-smaller-and-greater-elements',
    leetcodeUrl: leetCodeUrl('count-elements-with-strictly-smaller-and-greater-elements'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['min-max-exclusion'],
  },
  {
    id: '2154',
    title: 'Keep Multiplying Found Values by Two',
    slug: 'keep-multiplying-found-values-by-two',
    leetcodeUrl: leetCodeUrl('keep-multiplying-found-values-by-two'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['set-chase'],
  },
  {
    id: '2176',
    title: 'Count Equal and Divisible Pairs in an Array',
    slug: 'count-equal-and-divisible-pairs-in-an-array',
    leetcodeUrl: leetCodeUrl('count-equal-and-divisible-pairs-in-an-array'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['pair-enumeration'],
  },
  {
    id: '2190',
    title: 'Most Frequent Number Following Key In an Array',
    slug: 'most-frequent-number-following-key-in-an-array',
    leetcodeUrl: leetCodeUrl('most-frequent-number-following-key-in-an-array'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['successor-frequency'],
  },
  {
    id: '2206',
    title: 'Divide Array Into Equal Pairs',
    slug: 'divide-array-into-equal-pairs',
    leetcodeUrl: leetCodeUrl('divide-array-into-equal-pairs'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['frequency-parity'],
  },
  {
    id: '2215',
    title: 'Find the Difference of Two Arrays',
    slug: 'find-the-difference-of-two-arrays',
    leetcodeUrl: leetCodeUrl('find-the-difference-of-two-arrays'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['set-difference'],
  },
  {
    id: '2239',
    title: 'Find Closest Number to Zero',
    slug: 'find-closest-number-to-zero',
    leetcodeUrl: leetCodeUrl('find-closest-number-to-zero'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['abs-minimum'],
  },
  {
    id: '2248',
    title: 'Intersection of Multiple Arrays',
    slug: 'intersection-of-multiple-arrays',
    leetcodeUrl: leetCodeUrl('intersection-of-multiple-arrays'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['frequency-across-rows'],
  },
  {
    id: '2319',
    title: 'Check if Matrix Is X-Matrix',
    slug: 'check-if-matrix-is-x-matrix',
    leetcodeUrl: leetCodeUrl('check-if-matrix-is-x-matrix'),
    difficulty: 'Easy',
    dataStructures: ['matrix'],
    patterns: ['diagonal-check'],
  },
  {
    id: '2335',
    title: 'Minimum Amount of Time to Fill Cups',
    slug: 'minimum-amount-of-time-to-fill-cups',
    leetcodeUrl: leetCodeUrl('minimum-amount-of-time-to-fill-cups'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['greedy-pairing'],
  },
  {
    id: '2341',
    title: 'Maximum Number of Pairs in Array',
    slug: 'maximum-number-of-pairs-in-array',
    leetcodeUrl: leetCodeUrl('maximum-number-of-pairs-in-array'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['frequency-pairs'],
  },
  {
    id: '2347',
    title: 'Best Poker Hand',
    slug: 'best-poker-hand',
    leetcodeUrl: leetCodeUrl('best-poker-hand'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['rank-suit-counts'],
  },
  {
    id: '2357',
    title: 'Make Array Zero by Subtracting Equal Amounts',
    slug: 'make-array-zero-by-subtracting-equal-amounts',
    leetcodeUrl: leetCodeUrl('make-array-zero-by-subtracting-equal-amounts'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['distinct-positives'],
  },
  {
    id: '2367',
    title: 'Number of Arithmetic Triplets',
    slug: 'number-of-arithmetic-triplets',
    leetcodeUrl: leetCodeUrl('number-of-arithmetic-triplets'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['triplet-enumeration'],
  },
  {
    id: '2383',
    title: 'Minimum Hours of Training to Win a Competition',
    slug: 'minimum-hours-of-training-to-win-a-competition',
    leetcodeUrl: leetCodeUrl('minimum-hours-of-training-to-win-a-competition'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['greedy-simulation'],
  },
  {
    id: '2389',
    title: 'Longest Subsequence With Limited Sum',
    slug: 'longest-subsequence-with-limited-sum',
    leetcodeUrl: leetCodeUrl('longest-subsequence-with-limited-sum'),
    difficulty: 'Easy',
    dataStructures: ['array', 'sorting'],
    patterns: ['sort-prefix-binary-search'],
  },
  {
    id: '2395',
    title: 'Find Subarrays With Equal Sum',
    slug: 'find-subarrays-with-equal-sum',
    leetcodeUrl: leetCodeUrl('find-subarrays-with-equal-sum'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['seen-sums'],
  },
  {
    id: '2404',
    title: 'Most Frequent Even Element',
    slug: 'most-frequent-even-element',
    leetcodeUrl: leetCodeUrl('most-frequent-even-element'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['frequency-max'],
  },
  {
    id: '2418',
    title: 'Sort the People',
    slug: 'sort-the-people',
    leetcodeUrl: leetCodeUrl('sort-the-people'),
    difficulty: 'Easy',
    dataStructures: ['array', 'sorting'],
    patterns: ['paired-sort'],
  },
  {
    id: '2432',
    title: 'The Employee That Worked on the Longest Task',
    slug: 'the-employee-that-worked-on-the-longest-task',
    leetcodeUrl: leetCodeUrl('the-employee-that-worked-on-the-longest-task'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['max-duration-scan'],
  },
  {
    id: '2441',
    title: 'Largest Positive Integer That Exists With Its Negative',
    slug: 'largest-positive-integer-that-exists-with-its-negative',
    leetcodeUrl: leetCodeUrl('largest-positive-integer-that-exists-with-its-negative'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['mirror-set'],
  },
  {
    id: '2455',
    title: 'Average Value of Even Numbers That Are Divisible by Three',
    slug: 'average-value-of-even-numbers-that-are-divisible-by-three',
    leetcodeUrl: leetCodeUrl('average-value-of-even-numbers-that-are-divisible-by-three'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['filter-average'],
  },
  {
    id: '2460',
    title: 'Apply Operations to an Array',
    slug: 'apply-operations-to-an-array',
    leetcodeUrl: leetCodeUrl('apply-operations-to-an-array'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['merge-shift'],
  },
  {
    id: '2465',
    title: 'Number of Distinct Averages',
    slug: 'number-of-distinct-averages',
    leetcodeUrl: leetCodeUrl('number-of-distinct-averages'),
    difficulty: 'Easy',
    dataStructures: ['array', 'sorting'],
    patterns: ['pair-sums-set'],
  },
  {
    id: '2475',
    title: 'Number of Unequal Triplets in Array',
    slug: 'number-of-unequal-triplets-in-array',
    leetcodeUrl: leetCodeUrl('number-of-unequal-triplets-in-array'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['triplet-enumeration'],
  },
  {
    id: '2485',
    title: 'Find the Pivot Integer',
    slug: 'find-the-pivot-integer',
    leetcodeUrl: leetCodeUrl('find-the-pivot-integer'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['prefix-balance'],
  },
  {
    id: '2500',
    title: 'Delete Greatest Value in Each Row',
    slug: 'delete-greatest-value-in-each-row',
    leetcodeUrl: leetCodeUrl('delete-greatest-value-in-each-row'),
    difficulty: 'Easy',
    dataStructures: ['matrix', 'sorting'],
    patterns: ['sort-rows-max'],
  },
  {
    id: '2511',
    title: 'Maximum Enemy Forts That Can Be Captured',
    slug: 'maximum-enemy-forts-that-can-be-captured',
    leetcodeUrl: leetCodeUrl('maximum-enemy-forts-that-can-be-captured'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['segment-scan'],
  },
  {
    id: '2515',
    title: 'Shortest Distance to Target String in a Circular Array',
    slug: 'shortest-distance-to-target-string-in-a-circular-array',
    leetcodeUrl: leetCodeUrl('shortest-distance-to-target-string-in-a-circular-array'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['circular-distance'],
  },
  {
    id: '2529',
    title: 'Maximum Count of Positive Integer and Negative Integer',
    slug: 'maximum-count-of-positive-integer-and-negative-integer',
    leetcodeUrl: leetCodeUrl('maximum-count-of-positive-integer-and-negative-integer'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['binary-search-bounds'],
  },
  {
    id: '2535',
    title: 'Difference Between Element Sum and Digit Sum of an Array',
    slug: 'difference-between-element-sum-and-digit-sum-of-an-array',
    leetcodeUrl: leetCodeUrl('difference-between-element-sum-and-digit-sum-of-an-array'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['digit-sum'],
  },
  {
    id: '2540',
    title: 'Minimum Common Value',
    slug: 'minimum-common-value',
    leetcodeUrl: leetCodeUrl('minimum-common-value'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['two-pointers-intersection'],
  },
  {
    id: '2553',
    title: 'Separate the Digits in an Array',
    slug: 'separate-the-digits-in-an-array',
    leetcodeUrl: leetCodeUrl('separate-the-digits-in-an-array'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['digit-split'],
  },
  {
    id: '2562',
    title: 'Find the Array Concatenation Value',
    slug: 'find-the-array-concatenation-value',
    leetcodeUrl: leetCodeUrl('find-the-array-concatenation-value'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['two-ends-concat'],
  },
  {
    id: '2570',
    title: 'Merge Two 2D Arrays by Summing Values',
    slug: 'merge-two-2d-arrays-by-summing-values',
    leetcodeUrl: leetCodeUrl('merge-two-2d-arrays-by-summing-values'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['merge-by-key'],
  },
  {
    id: '2574',
    title: 'Left and Right Sum Differences',
    slug: 'left-and-right-sum-differences',
    leetcodeUrl: leetCodeUrl('left-and-right-sum-differences'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['prefix-suffix'],
  },
  {
    id: '2582',
    title: 'Pass the Pillow',
    slug: 'pass-the-pillow',
    leetcodeUrl: leetCodeUrl('pass-the-pillow'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['bounce-simulation'],
  },
  {
    id: '2643',
    title: 'Row With Maximum Ones',
    slug: 'row-with-maximum-ones',
    leetcodeUrl: leetCodeUrl('row-with-maximum-ones'),
    difficulty: 'Easy',
    dataStructures: ['matrix'],
    patterns: ['row-sums'],
  },
  {
    id: '2656',
    title: 'Maximum Sum With Exactly K Elements',
    slug: 'maximum-sum-with-exactly-k-elements',
    leetcodeUrl: leetCodeUrl('maximum-sum-with-exactly-k-elements'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['max-plus-sequence'],
  },
  {
    id: '2657',
    title: 'Find the Prefix Common Array of Two Arrays',
    slug: 'find-the-prefix-common-array-of-two-arrays',
    leetcodeUrl: leetCodeUrl('find-the-prefix-common-array-of-two-arrays'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['prefix-common-count'],
  },
  {
    id: '2660',
    title: 'Determine the Winner of a Bowling Game',
    slug: 'determine-the-winner-of-a-bowling-game',
    leetcodeUrl: leetCodeUrl('determine-the-winner-of-a-bowling-game'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['strike-bonus'],
  },
  {
    id: '2678',
    title: 'Number of Senior Citizens',
    slug: 'number-of-senior-citizens',
    leetcodeUrl: leetCodeUrl('number-of-senior-citizens'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['fixed-format-parse'],
  },
  {
    id: '2682',
    title: 'Find the Losers of the Circular Game',
    slug: 'find-the-losers-of-the-circular-game',
    leetcodeUrl: leetCodeUrl('find-the-losers-of-the-circular-game'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['visited-simulation'],
  },
  {
    id: '2706',
    title: 'Buy Two Chocolates',
    slug: 'buy-two-chocolates',
    leetcodeUrl: leetCodeUrl('buy-two-chocolates'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['two-minimums'],
  },
  {
    id: '2733',
    title: 'Neither Minimum nor Maximum',
    slug: 'neither-minimum-nor-maximum',
    leetcodeUrl: leetCodeUrl('neither-minimum-nor-maximum'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['median-of-three'],
  },
  {
    id: '2760',
    title: 'Longest Even Odd Subarray With Threshold',
    slug: 'longest-even-odd-subarray-with-threshold',
    leetcodeUrl: leetCodeUrl('longest-even-odd-subarray-with-threshold'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['alternating-runs'],
  },
  {
    id: '2765',
    title: 'Longest Alternating Subarray',
    slug: 'longest-alternating-subarray',
    leetcodeUrl: leetCodeUrl('longest-alternating-subarray'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['alternating-runs'],
  },
  {
    id: '2769',
    title: 'Find the Width of Columns of a Grid',
    slug: 'find-the-width-of-columns-of-a-grid',
    leetcodeUrl: leetCodeUrl('find-the-width-of-columns-of-a-grid'),
    difficulty: 'Easy',
    dataStructures: ['matrix'],
    patterns: ['column-widths'],
  },
  {
    id: '2778',
    title: 'Sum of Squares of Special Elements',
    slug: 'sum-of-squares-of-special-elements',
    leetcodeUrl: leetCodeUrl('sum-of-squares-of-special-elements'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['divisor-indices'],
  },
  {
    id: '2784',
    title: 'Check if Array is Good',
    slug: 'check-if-array-is-good',
    leetcodeUrl: leetCodeUrl('check-if-array-is-good'),
    difficulty: 'Easy',
    dataStructures: ['array', 'sorting'],
    patterns: ['permutation-check'],
  },
  {
    id: '2798',
    title: 'Number of Employees Who Met the Target',
    slug: 'number-of-employees-who-met-the-target',
    leetcodeUrl: leetCodeUrl('number-of-employees-who-met-the-target'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['threshold-count'],
  },
  {
    id: '2815',
    title: 'Max Pair Sum in an Array',
    slug: 'max-pair-sum-in-an-array',
    leetcodeUrl: leetCodeUrl('max-pair-sum-in-an-array'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['max-digit-pairs'],
  },
  {
    id: '2824',
    title: 'Count Pairs Whose Sum is Less than Target',
    slug: 'count-pairs-whose-sum-is-less-than-target',
    leetcodeUrl: leetCodeUrl('count-pairs-whose-sum-is-less-than-target'),
    difficulty: 'Easy',
    dataStructures: ['array', 'sorting'],
    patterns: ['two-pointers-count'],
  },
  {
    id: '2833',
    title: 'Furthest Point From Origin',
    slug: 'furthest-point-from-origin',
    leetcodeUrl: leetCodeUrl('furthest-point-from-origin'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['displacement-wildcards'],
  },
  {
    id: '2855',
    title: 'Minimum Right Shifts to Sort the Array',
    slug: 'minimum-right-shifts-to-sort-the-array',
    leetcodeUrl: leetCodeUrl('minimum-right-shifts-to-sort-the-array'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['rotation-point'],
  },
  {
    id: '2869',
    title: 'Minimum Operations to Collect Elements',
    slug: 'minimum-operations-to-collect-elements',
    leetcodeUrl: leetCodeUrl('minimum-operations-to-collect-elements'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['suffix-collect'],
  },
  {
    id: '2873',
    title: 'Maximum Value of an Ordered Triplet I',
    slug: 'maximum-value-of-an-ordered-triplet-i',
    leetcodeUrl: leetCodeUrl('maximum-value-of-an-ordered-triplet-i'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['triplet-enumeration'],
  },
  {
    id: '2899',
    title: 'Last Visited Integers',
    slug: 'last-visited-integers',
    leetcodeUrl: leetCodeUrl('last-visited-integers'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['history-pointer'],
  },
  {
    id: '2903',
    title: 'Find Indices With Index and Value Difference I',
    slug: 'find-indices-with-index-and-value-difference-i',
    leetcodeUrl: leetCodeUrl('find-indices-with-index-and-value-difference-i'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['pair-enumeration'],
  },
  {
    id: '2923',
    title: 'Find Champion I',
    slug: 'find-champion-i',
    leetcodeUrl: leetCodeUrl('find-champion-i'),
    difficulty: 'Easy',
    dataStructures: ['matrix'],
    patterns: ['row-dominance'],
  },
  {
    id: '2946',
    title: 'Matrix Similarity After Cyclic Shifts',
    slug: 'matrix-similarity-after-cyclic-shifts',
    leetcodeUrl: leetCodeUrl('matrix-similarity-after-cyclic-shifts'),
    difficulty: 'Easy',
    dataStructures: ['matrix'],
    patterns: ['shift-compare'],
  },
  {
    id: '2951',
    title: 'Find the Peaks',
    slug: 'find-the-peaks',
    leetcodeUrl: leetCodeUrl('find-the-peaks'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['neighbor-compare'],
  },
  {
    id: '2956',
    title: 'Find Common Elements Between Two Arrays',
    slug: 'find-common-elements-between-two-arrays',
    leetcodeUrl: leetCodeUrl('find-common-elements-between-two-arrays'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['set-membership-counts'],
  },
  {
    id: '2960',
    title: 'Count Tested Devices After Test Operations',
    slug: 'count-tested-devices-after-test-operations',
    leetcodeUrl: leetCodeUrl('count-tested-devices-after-test-operations'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['decrement-simulation'],
  },
  {
    id: '2965',
    title: 'Find Missing and Repeated Values',
    slug: 'find-missing-and-repeated-values',
    leetcodeUrl: leetCodeUrl('find-missing-and-repeated-values'),
    difficulty: 'Easy',
    dataStructures: ['matrix', 'hash-table'],
    patterns: ['frequency-scan'],
  },
  {
    id: '2974',
    title: 'Minimum Number Game',
    slug: 'minimum-number-game',
    leetcodeUrl: leetCodeUrl('minimum-number-game'),
    difficulty: 'Easy',
    dataStructures: ['array', 'sorting'],
    patterns: ['sort-pair-swap'],
  },
  {
    id: '3000',
    title: 'Maximum Area of Longest Diagonal Rectangle',
    slug: 'maximum-area-of-longest-diagonal-rectangle',
    leetcodeUrl: leetCodeUrl('maximum-area-of-longest-diagonal-rectangle'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['diagonal-compare'],
  },
  {
    id: '3005',
    title: 'Count Elements With Maximum Frequency',
    slug: 'count-elements-with-maximum-frequency',
    leetcodeUrl: leetCodeUrl('count-elements-with-maximum-frequency'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['frequency-max'],
  },
  {
    id: '3010',
    title: 'Divide an Array Into Subarrays With Minimum Cost I',
    slug: 'divide-an-array-into-subarrays-with-minimum-cost-i',
    leetcodeUrl: leetCodeUrl('divide-an-array-into-subarrays-with-minimum-cost-i'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['two-minimums'],
  },
  {
    id: '3028',
    title: 'Ant on the Boundary',
    slug: 'ant-on-the-boundary',
    leetcodeUrl: leetCodeUrl('ant-on-the-boundary'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['prefix-returns'],
  },
  {
    id: '3033',
    title: 'Modify the Matrix',
    slug: 'modify-the-matrix',
    leetcodeUrl: leetCodeUrl('modify-the-matrix'),
    difficulty: 'Easy',
    dataStructures: ['matrix'],
    patterns: ['column-maximums'],
  },
  {
    id: '3046',
    title: 'Split the Array',
    slug: 'split-the-array',
    leetcodeUrl: leetCodeUrl('split-the-array'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['frequency-cap'],
  },
  // ----- Medium -----
  {
    id: '238',
    title: 'Product of Array Except Self',
    slug: 'product-of-array-except-self',
    leetcodeUrl: leetCodeUrl('product-of-array-except-self'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['prefix-suffix-passes'],
  },
  {
    id: '128',
    title: 'Longest Consecutive Sequence',
    slug: 'longest-consecutive-sequence',
    leetcodeUrl: leetCodeUrl('longest-consecutive-sequence'),
    difficulty: 'Medium',
    dataStructures: ['array', 'hash-table'],
    patterns: ['streak-starts'],
  },
  {
    id: '53',
    title: 'Maximum Subarray',
    slug: 'maximum-subarray',
    leetcodeUrl: leetCodeUrl('maximum-subarray'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['kadane'],
  },
  {
    id: '152',
    title: 'Maximum Product Subarray',
    slug: 'maximum-product-subarray',
    leetcodeUrl: leetCodeUrl('maximum-product-subarray'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['track-min-max'],
  },
  {
    id: '153',
    title: 'Find Minimum in Rotated Sorted Array',
    slug: 'find-minimum-in-rotated-sorted-array',
    leetcodeUrl: leetCodeUrl('find-minimum-in-rotated-sorted-array'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['rotated-binary-search'],
  },
  {
    id: '33',
    title: 'Search in Rotated Sorted Array',
    slug: 'search-in-rotated-sorted-array',
    leetcodeUrl: leetCodeUrl('search-in-rotated-sorted-array'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['rotated-binary-search'],
  },
  {
    id: '167',
    title: 'Two Sum II - Input Array Is Sorted',
    slug: 'two-sum-ii-input-array-is-sorted',
    leetcodeUrl: leetCodeUrl('two-sum-ii-input-array-is-sorted'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['two-pointers-converge'],
  },
  {
    id: '15',
    title: '3Sum',
    slug: '3sum',
    leetcodeUrl: leetCodeUrl('3sum'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['sort-plus-two-pointers'],
  },
  {
    id: '16',
    title: '3Sum Closest',
    slug: '3sum-closest',
    leetcodeUrl: leetCodeUrl('3sum-closest'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['sort-plus-two-pointers'],
  },
  {
    id: '18',
    title: '4Sum',
    slug: '4sum',
    leetcodeUrl: leetCodeUrl('4sum'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['sort-plus-nested-loops'],
  },
  {
    id: '11',
    title: 'Container With Most Water',
    slug: 'container-with-most-water',
    leetcodeUrl: leetCodeUrl('container-with-most-water'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['two-pointers-converge'],
  },
  {
    id: '287',
    title: 'Find the Duplicate Number',
    slug: 'find-the-duplicate-number',
    leetcodeUrl: leetCodeUrl('find-the-duplicate-number'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['floyd-cycle'],
  },
  {
    id: '560',
    title: 'Subarray Sum Equals K',
    slug: 'subarray-sum-equals-k',
    leetcodeUrl: leetCodeUrl('subarray-sum-equals-k'),
    difficulty: 'Medium',
    dataStructures: ['array', 'hash-table'],
    patterns: ['prefix-frequency'],
  },
  {
    id: '523',
    title: 'Continuous Subarray Sum',
    slug: 'continuous-subarray-sum',
    leetcodeUrl: leetCodeUrl('continuous-subarray-sum'),
    difficulty: 'Medium',
    dataStructures: ['array', 'hash-table'],
    patterns: ['prefix-modulo'],
  },
  {
    id: '974',
    title: 'Subarray Sums Divisible by K',
    slug: 'subarray-sums-divisible-by-k',
    leetcodeUrl: leetCodeUrl('subarray-sums-divisible-by-k'),
    difficulty: 'Medium',
    dataStructures: ['array', 'hash-table'],
    patterns: ['prefix-modulo'],
  },
  {
    id: '55',
    title: 'Jump Game',
    slug: 'jump-game',
    leetcodeUrl: leetCodeUrl('jump-game'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['greedy-reach'],
  },
  {
    id: '45',
    title: 'Jump Game II',
    slug: 'jump-game-ii',
    leetcodeUrl: leetCodeUrl('jump-game-ii'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['greedy-jumps'],
  },
  {
    id: '134',
    title: 'Gas Station',
    slug: 'gas-station',
    leetcodeUrl: leetCodeUrl('gas-station'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['circular-greedy'],
  },
  {
    id: '274',
    title: 'H-Index',
    slug: 'h-index',
    leetcodeUrl: leetCodeUrl('h-index'),
    difficulty: 'Medium',
    dataStructures: ['array', 'sorting'],
    patterns: ['citation-count'],
  },
  {
    id: '56',
    title: 'Merge Intervals',
    slug: 'merge-intervals',
    leetcodeUrl: leetCodeUrl('merge-intervals'),
    difficulty: 'Medium',
    dataStructures: ['array', 'sorting'],
    patterns: ['sort-merge-overlaps'],
  },
  {
    id: '57',
    title: 'Insert Interval',
    slug: 'insert-interval',
    leetcodeUrl: leetCodeUrl('insert-interval'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['insert-merge'],
  },
  {
    id: '1899',
    title: 'Merge Triplets to Form Target Triplet',
    slug: 'merge-triplets-to-form-target-triplet',
    leetcodeUrl: leetCodeUrl('merge-triplets-to-form-target-triplet'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['greedy-triplet-cover'],
  },
  {
    id: '31',
    title: 'Next Permutation',
    slug: 'next-permutation',
    leetcodeUrl: leetCodeUrl('next-permutation'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['pivot-swap-reverse'],
  },
  {
    id: '334',
    title: 'Increasing Triplet Subsequence',
    slug: 'increasing-triplet-subsequence',
    leetcodeUrl: leetCodeUrl('increasing-triplet-subsequence'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['two-minimums'],
  },
  {
    id: '442',
    title: 'Find All Duplicates in an Array',
    slug: 'find-all-duplicates-in-an-array',
    leetcodeUrl: leetCodeUrl('find-all-duplicates-in-an-array'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['index-marking'],
  },
  {
    id: '670',
    title: 'Maximum Swap',
    slug: 'maximum-swap',
    leetcodeUrl: leetCodeUrl('maximum-swap'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['last-max-swap'],
  },
  {
    id: '667',
    title: 'Beautiful Arrangement II',
    slug: 'beautiful-arrangement-ii',
    leetcodeUrl: leetCodeUrl('beautiful-arrangement-ii'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['alternating-extremes'],
  },
  {
    id: '665',
    title: 'Non-decreasing Array',
    slug: 'non-decreasing-array',
    leetcodeUrl: leetCodeUrl('non-decreasing-array'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['one-fix-check'],
  },
  {
    id: '624',
    title: 'Maximum Distance in Arrays',
    slug: 'maximum-distance-in-arrays',
    leetcodeUrl: leetCodeUrl('maximum-distance-in-arrays'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['global-min-max'],
  },
  {
    id: '628',
    title: 'Maximum Product of Three Numbers',
    slug: 'maximum-product-of-three-numbers',
    leetcodeUrl: leetCodeUrl('maximum-product-of-three-numbers'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['extremes-product'],
  },
  {
    id: '915',
    title: 'Partition Array into Disjoint Intervals',
    slug: 'partition-array-into-disjoint-intervals',
    leetcodeUrl: leetCodeUrl('partition-array-into-disjoint-intervals'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['left-max-scan'],
  },
  {
    id: '918',
    title: 'Maximum Sum Circular Subarray',
    slug: 'maximum-sum-circular-subarray',
    leetcodeUrl: leetCodeUrl('maximum-sum-circular-subarray'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['kadane-wrap'],
  },
  {
    id: '1014',
    title: 'Best Sightseeing Pair',
    slug: 'best-sightseeing-pair',
    leetcodeUrl: leetCodeUrl('best-sightseeing-pair'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['best-left-scan'],
  },
  {
    id: '1749',
    title: 'Maximum Absolute Sum of Any Subarray',
    slug: 'maximum-absolute-sum-of-any-subarray',
    leetcodeUrl: leetCodeUrl('maximum-absolute-sum-of-any-subarray'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['min-max-prefix'],
  },
  {
    id: '1856',
    title: 'Maximum Subarray Min-Product',
    slug: 'maximum-subarray-min-product',
    leetcodeUrl: leetCodeUrl('maximum-subarray-min-product'),
    difficulty: 'Medium',
    dataStructures: ['array', 'stack'],
    patterns: ['monotonic-boundaries'],
  },
  {
    id: '1109',
    title: 'Corporate Flight Bookings',
    slug: 'corporate-flight-bookings',
    leetcodeUrl: leetCodeUrl('corporate-flight-bookings'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['difference-array'],
  },
  {
    id: '1094',
    title: 'Car Pooling',
    slug: 'car-pooling',
    leetcodeUrl: leetCodeUrl('car-pooling'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['difference-array'],
  },
  {
    id: '1310',
    title: 'XOR Queries of a Subarray',
    slug: 'xor-queries-of-a-subarray',
    leetcodeUrl: leetCodeUrl('xor-queries-of-a-subarray'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['prefix-xor'],
  },
  {
    id: '1681',
    title: 'Sum of Absolute Differences in a Sorted Array',
    slug: 'sum-of-absolute-differences-in-a-sorted-array',
    leetcodeUrl: leetCodeUrl('sum-of-absolute-differences-in-a-sorted-array'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['prefix-two-sides'],
  },
  {
    id: '1658',
    title: 'Minimum Operations to Reduce X to Zero',
    slug: 'minimum-operations-to-reduce-x-to-zero',
    leetcodeUrl: leetCodeUrl('minimum-operations-to-reduce-x-to-zero'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['complement-subarray'],
  },
  {
    id: '1423',
    title: 'Maximum Points You Can Obtain from Cards',
    slug: 'maximum-points-you-can-obtain-from-cards',
    leetcodeUrl: leetCodeUrl('maximum-points-you-can-obtain-from-cards'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['ends-window'],
  },
  {
    id: '1769',
    title: 'Minimum Number of Operations to Move All Balls to Each Box',
    slug: 'minimum-number-of-operations-to-move-all-balls-to-each-box',
    leetcodeUrl: leetCodeUrl('minimum-number-of-operations-to-move-all-balls-to-each-box'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['two-pass-counts'],
  },
  {
    id: '59',
    title: 'Spiral Matrix II',
    slug: 'spiral-matrix-ii',
    leetcodeUrl: leetCodeUrl('spiral-matrix-ii'),
    difficulty: 'Medium',
    dataStructures: ['matrix'],
    patterns: ['spiral-fill'],
  },
  {
    id: '289',
    title: 'Game of Life',
    slug: 'game-of-life',
    leetcodeUrl: leetCodeUrl('game-of-life'),
    difficulty: 'Medium',
    dataStructures: ['matrix'],
    patterns: ['in-place-states'],
  },
  {
    id: '885',
    title: 'Spiral Matrix III',
    slug: 'spiral-matrix-iii',
    leetcodeUrl: leetCodeUrl('spiral-matrix-iii'),
    difficulty: 'Medium',
    dataStructures: ['matrix'],
    patterns: ['spiral-walk'],
  },
  {
    id: '48',
    title: 'Rotate Image',
    slug: 'rotate-image',
    leetcodeUrl: leetCodeUrl('rotate-image'),
    difficulty: 'Medium',
    dataStructures: ['matrix'],
    patterns: ['transpose-reverse'],
  },
  {
    id: '54',
    title: 'Spiral Matrix',
    slug: 'spiral-matrix',
    leetcodeUrl: leetCodeUrl('spiral-matrix'),
    difficulty: 'Medium',
    dataStructures: ['matrix'],
    patterns: ['boundary-peel'],
  },
  {
    id: '73',
    title: 'Set Matrix Zeroes',
    slug: 'set-matrix-zeroes',
    leetcodeUrl: leetCodeUrl('set-matrix-zeroes'),
    difficulty: 'Medium',
    dataStructures: ['matrix'],
    patterns: ['marker-row-col'],
  },
  {
    id: '74',
    title: 'Search a 2D Matrix',
    slug: 'search-a-2d-matrix',
    leetcodeUrl: leetCodeUrl('search-a-2d-matrix'),
    difficulty: 'Medium',
    dataStructures: ['matrix'],
    patterns: ['flat-binary-search'],
  },
  {
    id: '581',
    title: 'Shortest Unsorted Continuous Subarray',
    slug: 'shortest-unsorted-continuous-subarray',
    leetcodeUrl: leetCodeUrl('shortest-unsorted-continuous-subarray'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['sorted-compare-bounds'],
  },
  {
    id: '456',
    title: '132 Pattern',
    slug: '132-pattern',
    leetcodeUrl: leetCodeUrl('132-pattern'),
    difficulty: 'Medium',
    dataStructures: ['array', 'stack'],
    patterns: ['monotonic-scan'],
  },
  {
    id: '769',
    title: 'Max Chunks To Make Sorted',
    slug: 'max-chunks-to-make-sorted',
    leetcodeUrl: leetCodeUrl('max-chunks-to-make-sorted'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['prefix-max-chunks'],
  },
  {
    id: '768',
    title: 'Max Chunks To Make Sorted II',
    slug: 'max-chunks-to-make-sorted-ii',
    leetcodeUrl: leetCodeUrl('max-chunks-to-make-sorted-ii'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['prefix-max-chunks'],
  },
  {
    id: '1498',
    title: 'Number of Subarrays of Size K and Average Greater than or Equal to Threshold',
    slug: 'number-of-subarrays-of-size-k-and-average-greater-than-or-equal-to-threshold',
    leetcodeUrl: leetCodeUrl('number-of-subarrays-of-size-k-and-average-greater-than-or-equal-to-threshold'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['fixed-sliding-window'],
  },
  {
    id: '1208',
    title: 'Get Equal Substrings Within Budget',
    slug: 'get-equal-substrings-within-budget',
    leetcodeUrl: leetCodeUrl('get-equal-substrings-within-budget'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['cost-sliding-window'],
  },
  {
    id: '1004',
    title: 'Max Consecutive Ones III',
    slug: 'max-consecutive-ones-iii',
    leetcodeUrl: leetCodeUrl('max-consecutive-ones-iii'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['flips-sliding-window'],
  },
  {
    id: '904',
    title: 'Fruit Into Baskets',
    slug: 'fruit-into-baskets',
    leetcodeUrl: leetCodeUrl('fruit-into-baskets'),
    difficulty: 'Medium',
    dataStructures: ['array', 'hash-table'],
    patterns: ['two-type-window'],
  },
  {
    id: '978',
    title: 'Longest Turbulent Subarray',
    slug: 'longest-turbulent-subarray',
    leetcodeUrl: leetCodeUrl('longest-turbulent-subarray'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['sign-alternation'],
  },
  {
    id: '845',
    title: 'Longest Mountain in Array',
    slug: 'longest-mountain-in-array',
    leetcodeUrl: leetCodeUrl('longest-mountain-in-array'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['up-down-runs'],
  },
  {
    id: '674',
    title: 'Longest Continuous Increasing Subsequence',
    slug: 'longest-continuous-increasing-subsequence',
    leetcodeUrl: leetCodeUrl('longest-continuous-increasing-subsequence'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['increasing-runs'],
  },
  {
    id: '849',
    title: 'Maximize Distance to Closest Person',
    slug: 'maximize-distance-to-closest-person',
    leetcodeUrl: leetCodeUrl('maximize-distance-to-closest-person'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['gap-halving'],
  },
  // ----- Hard -----
  {
    id: '42',
    title: 'Trapping Rain Water',
    slug: 'trapping-rain-water',
    leetcodeUrl: leetCodeUrl('trapping-rain-water'),
    difficulty: 'Hard',
    dataStructures: ['array'],
    patterns: ['two-pointers-water'],
  },
  {
    id: '41',
    title: 'First Missing Positive',
    slug: 'first-missing-positive',
    leetcodeUrl: leetCodeUrl('first-missing-positive'),
    difficulty: 'Hard',
    dataStructures: ['array'],
    patterns: ['index-placement'],
  },
  {
    id: '85',
    title: 'Maximal Rectangle',
    slug: 'maximal-rectangle',
    leetcodeUrl: leetCodeUrl('maximal-rectangle'),
    difficulty: 'Hard',
    dataStructures: ['matrix', 'stack'],
    patterns: ['histogram-rows'],
  },
  {
    id: '315',
    title: 'Count of Smaller Numbers After Self',
    slug: 'count-of-smaller-numbers-after-self',
    leetcodeUrl: leetCodeUrl('count-of-smaller-numbers-after-self'),
    difficulty: 'Hard',
    dataStructures: ['array'],
    patterns: ['merge-sort-count'],
  },
  {
    id: '330',
    title: 'Patching Array',
    slug: 'patching-array',
    leetcodeUrl: leetCodeUrl('patching-array'),
    difficulty: 'Hard',
    dataStructures: ['array'],
    patterns: ['reachable-range'],
  },
  {
    id: '719',
    title: 'Find K-th Smallest Pair Distance',
    slug: 'find-k-th-smallest-pair-distance',
    leetcodeUrl: leetCodeUrl('find-k-th-smallest-pair-distance'),
    difficulty: 'Hard',
    dataStructures: ['array'],
    patterns: ['binary-search-count'],
  },
  {
    id: '786',
    title: 'K-th Smallest Prime Fraction',
    slug: 'k-th-smallest-prime-fraction',
    leetcodeUrl: leetCodeUrl('k-th-smallest-prime-fraction'),
    difficulty: 'Hard',
    dataStructures: ['array', 'heap'],
    patterns: ['binary-search-count'],
  },
  {
    id: '878',
    title: 'Nth Magical Number',
    slug: 'nth-magical-number',
    leetcodeUrl: leetCodeUrl('nth-magical-number'),
    difficulty: 'Hard',
    dataStructures: ['array'],
    patterns: ['binary-search-count'],
  },
  {
    id: '936',
    title: 'Stamping The Sequence',
    slug: 'stamping-the-sequence',
    leetcodeUrl: leetCodeUrl('stamping-the-sequence'),
    difficulty: 'Hard',
    dataStructures: ['array'],
    patterns: ['reverse-greedy'],
  },
  {
    id: '995',
    title: 'Minimum Number of K Consecutive Bit Flips',
    slug: 'minimum-number-of-k-consecutive-bit-flips',
    leetcodeUrl: leetCodeUrl('minimum-number-of-k-consecutive-bit-flips'),
    difficulty: 'Hard',
    dataStructures: ['array'],
    patterns: ['difference-flips'],
  },
  {
    id: '1521',
    title: 'Find a Value of a Mysterious Function Closest to Target',
    slug: 'find-a-value-of-a-mysterious-function-closest-to-target',
    leetcodeUrl: leetCodeUrl('find-a-value-of-a-mysterious-function-closest-to-target'),
    difficulty: 'Hard',
    dataStructures: ['array'],
    patterns: ['distinct-ands'],
  },
  {
    id: '2106',
    title: 'Maximum Fruits Harvested After at Most K Steps',
    slug: 'maximum-fruits-harvested-after-at-most-k-steps',
    leetcodeUrl: leetCodeUrl('maximum-fruits-harvested-after-at-most-k-steps'),
    difficulty: 'Hard',
    dataStructures: ['array'],
    patterns: ['prefix-two-directions'],
  },
  {
    id: '2444',
    title: 'Count Subarrays With Fixed Bounds',
    slug: 'count-subarrays-with-fixed-bounds',
    leetcodeUrl: leetCodeUrl('count-subarrays-with-fixed-bounds'),
    difficulty: 'Hard',
    dataStructures: ['array'],
    patterns: ['bound-positions'],
  },
];
