import type { Problem } from '../../types/content.ts';
import { leetCodeUrl } from '../../types/content.ts';

/**
 * The full practice bank (NeetCode 150 + extras). Every slug is a real
 * LeetCode problem. `id` always equals `slug` so topic `problemIds`
 * resolve through `getProblem`.
 */
export const neetcodeProblems: Problem[] = [
  // ----- Arrays & Hashing -----
  {
    id: 'contains-duplicate',
    title: 'Contains Duplicate',
    slug: 'contains-duplicate',
    leetcodeUrl: leetCodeUrl('contains-duplicate'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['seen-set'],
  },
  {
    id: 'valid-anagram',
    title: 'Valid Anagram',
    slug: 'valid-anagram',
    leetcodeUrl: leetCodeUrl('valid-anagram'),
    difficulty: 'Easy',
    dataStructures: ['string', 'hash-table'],
    patterns: ['frequency-count'],
  },
  {
    id: 'two-sum',
    title: 'Two Sum',
    slug: 'two-sum',
    leetcodeUrl: leetCodeUrl('two-sum'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['hash-map-complement'],
  },
  {
    id: 'group-anagrams',
    title: 'Group Anagrams',
    slug: 'group-anagrams',
    leetcodeUrl: leetCodeUrl('group-anagrams'),
    difficulty: 'Medium',
    dataStructures: ['string', 'hash-table'],
    patterns: ['sorted-key-grouping'],
  },
  {
    id: 'top-k-frequent-elements',
    title: 'Top K Frequent Elements',
    slug: 'top-k-frequent-elements',
    leetcodeUrl: leetCodeUrl('top-k-frequent-elements'),
    difficulty: 'Medium',
    dataStructures: ['array', 'hash-table', 'heap'],
    patterns: ['bucket-or-heap'],
  },
  {
    id: 'product-of-array-except-self',
    title: 'Product of Array Except Self',
    slug: 'product-of-array-except-self',
    leetcodeUrl: leetCodeUrl('product-of-array-except-self'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['prefix-suffix-passes'],
  },
  {
    id: 'valid-sudoku',
    title: 'Valid Sudoku',
    slug: 'valid-sudoku',
    leetcodeUrl: leetCodeUrl('valid-sudoku'),
    difficulty: 'Medium',
    dataStructures: ['matrix', 'hash-table'],
    patterns: ['box-index-math'],
  },
  {
    id: 'longest-consecutive-sequence',
    title: 'Longest Consecutive Sequence',
    slug: 'longest-consecutive-sequence',
    leetcodeUrl: leetCodeUrl('longest-consecutive-sequence'),
    difficulty: 'Medium',
    dataStructures: ['array', 'hash-table'],
    patterns: ['sequence-start-check'],
  },
  {
    id: 'encode-and-decode-strings',
    title: 'Encode and Decode Strings',
    slug: 'encode-and-decode-strings',
    leetcodeUrl: leetCodeUrl('encode-and-decode-strings'),
    difficulty: 'Medium',
    dataStructures: ['string'],
    patterns: ['length-prefix-encoding'],
  },
  // ----- Two Pointers -----
  {
    id: 'valid-palindrome',
    title: 'Valid Palindrome',
    slug: 'valid-palindrome',
    leetcodeUrl: leetCodeUrl('valid-palindrome'),
    difficulty: 'Easy',
    dataStructures: ['string'],
    patterns: ['two-pointers-inward'],
  },
  {
    id: 'two-sum-ii-input-array-is-sorted',
    title: 'Two Sum II - Input Array Is Sorted',
    slug: 'two-sum-ii-input-array-is-sorted',
    leetcodeUrl: leetCodeUrl('two-sum-ii-input-array-is-sorted'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['converging-pointers'],
  },
  {
    id: '3sum',
    title: '3Sum',
    slug: '3sum',
    leetcodeUrl: leetCodeUrl('3sum'),
    difficulty: 'Medium',
    dataStructures: ['array', 'sorting'],
    patterns: ['sort-plus-converging'],
  },
  {
    id: 'container-with-most-water',
    title: 'Container With Most Water',
    slug: 'container-with-most-water',
    leetcodeUrl: leetCodeUrl('container-with-most-water'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['converging-pointers'],
  },
  {
    id: 'trapping-rain-water',
    title: 'Trapping Rain Water',
    slug: 'trapping-rain-water',
    leetcodeUrl: leetCodeUrl('trapping-rain-water'),
    difficulty: 'Hard',
    dataStructures: ['array', 'stack'],
    patterns: ['monotonic-valleys'],
  },
  // ----- Sliding Window -----
  {
    id: 'best-time-to-buy-and-sell-stock',
    title: 'Best Time to Buy and Sell Stock',
    slug: 'best-time-to-buy-and-sell-stock',
    leetcodeUrl: leetCodeUrl('best-time-to-buy-and-sell-stock'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['one-pass-min-tracking'],
  },
  {
    id: 'longest-substring-without-repeating-characters',
    title: 'Longest Substring Without Repeating Characters',
    slug: 'longest-substring-without-repeating-characters',
    leetcodeUrl: leetCodeUrl('longest-substring-without-repeating-characters'),
    difficulty: 'Medium',
    dataStructures: ['string', 'hash-table'],
    patterns: ['sliding-window-last-seen'],
  },
  {
    id: 'longest-repeating-character-replacement',
    title: 'Longest Repeating Character Replacement',
    slug: 'longest-repeating-character-replacement',
    leetcodeUrl: leetCodeUrl('longest-repeating-character-replacement'),
    difficulty: 'Medium',
    dataStructures: ['string'],
    patterns: ['flexible-window'],
  },
  {
    id: 'permutation-in-string',
    title: 'Permutation in String',
    slug: 'permutation-in-string',
    leetcodeUrl: leetCodeUrl('permutation-in-string'),
    difficulty: 'Medium',
    dataStructures: ['string', 'hash-table'],
    patterns: ['fixed-window-counts'],
  },
  {
    id: 'minimum-window-substring',
    title: 'Minimum Window Substring',
    slug: 'minimum-window-substring',
    leetcodeUrl: leetCodeUrl('minimum-window-substring'),
    difficulty: 'Hard',
    dataStructures: ['string', 'hash-table'],
    patterns: ['flexible-window'],
  },
  {
    id: 'sliding-window-maximum',
    title: 'Sliding Window Maximum',
    slug: 'sliding-window-maximum',
    leetcodeUrl: leetCodeUrl('sliding-window-maximum'),
    difficulty: 'Hard',
    dataStructures: ['array', 'queue-deque'],
    patterns: ['monotonic-deque'],
  },
  // ----- Stack -----
  {
    id: 'valid-parentheses',
    title: 'Valid Parentheses',
    slug: 'valid-parentheses',
    leetcodeUrl: leetCodeUrl('valid-parentheses'),
    difficulty: 'Easy',
    dataStructures: ['stack', 'string'],
    patterns: ['push-openers'],
  },
  {
    id: 'min-stack',
    title: 'Min Stack',
    slug: 'min-stack',
    leetcodeUrl: leetCodeUrl('min-stack'),
    difficulty: 'Medium',
    dataStructures: ['stack'],
    patterns: ['auxiliary-min-stack'],
  },
  {
    id: 'evaluate-reverse-polish-notation',
    title: 'Evaluate Reverse Polish Notation',
    slug: 'evaluate-reverse-polish-notation',
    leetcodeUrl: leetCodeUrl('evaluate-reverse-polish-notation'),
    difficulty: 'Medium',
    dataStructures: ['stack'],
    patterns: ['postfix-eval'],
  },
  {
    id: 'generate-parentheses',
    title: 'Generate Parentheses',
    slug: 'generate-parentheses',
    leetcodeUrl: leetCodeUrl('generate-parentheses'),
    difficulty: 'Medium',
    dataStructures: ['string', 'stack'],
    patterns: ['backtrack-balance'],
  },
  {
    id: 'daily-temperatures',
    title: 'Daily Temperatures',
    slug: 'daily-temperatures',
    leetcodeUrl: leetCodeUrl('daily-temperatures'),
    difficulty: 'Medium',
    dataStructures: ['stack'],
    patterns: ['monotonic-stack'],
  },
  {
    id: 'car-fleet',
    title: 'Car Fleet',
    slug: 'car-fleet',
    leetcodeUrl: leetCodeUrl('car-fleet'),
    difficulty: 'Medium',
    dataStructures: ['stack', 'sorting'],
    patterns: ['time-to-target-stack'],
  },
  {
    id: 'largest-rectangle-in-histogram',
    title: 'Largest Rectangle in Histogram',
    slug: 'largest-rectangle-in-histogram',
    leetcodeUrl: leetCodeUrl('largest-rectangle-in-histogram'),
    difficulty: 'Hard',
    dataStructures: ['stack'],
    patterns: ['monotonic-boundaries'],
  },
  // ----- Binary Search -----
  {
    id: 'binary-search',
    title: 'Binary Search',
    slug: 'binary-search',
    leetcodeUrl: leetCodeUrl('binary-search'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['halving-range'],
  },
  {
    id: 'search-a-2d-matrix',
    title: 'Search a 2D Matrix',
    slug: 'search-a-2d-matrix',
    leetcodeUrl: leetCodeUrl('search-a-2d-matrix'),
    difficulty: 'Medium',
    dataStructures: ['matrix'],
    patterns: ['flattened-binary-search'],
  },
  {
    id: 'koko-eating-bananas',
    title: 'Koko Eating Bananas',
    slug: 'koko-eating-bananas',
    leetcodeUrl: leetCodeUrl('koko-eating-bananas'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['binary-search-answer'],
  },
  {
    id: 'find-minimum-in-rotated-sorted-array',
    title: 'Find Minimum in Rotated Sorted Array',
    slug: 'find-minimum-in-rotated-sorted-array',
    leetcodeUrl: leetCodeUrl('find-minimum-in-rotated-sorted-array'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['rotation-pivot'],
  },
  {
    id: 'search-in-rotated-sorted-array',
    title: 'Search in Rotated Sorted Array',
    slug: 'search-in-rotated-sorted-array',
    leetcodeUrl: leetCodeUrl('search-in-rotated-sorted-array'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['rotation-pivot'],
  },
  {
    id: 'time-based-key-value-store',
    title: 'Time Based Key-Value Store',
    slug: 'time-based-key-value-store',
    leetcodeUrl: leetCodeUrl('time-based-key-value-store'),
    difficulty: 'Medium',
    dataStructures: ['hash-table'],
    patterns: ['binary-search-timestamps'],
  },
  {
    id: 'median-of-two-sorted-arrays',
    title: 'Median of Two Sorted Arrays',
    slug: 'median-of-two-sorted-arrays',
    leetcodeUrl: leetCodeUrl('median-of-two-sorted-arrays'),
    difficulty: 'Hard',
    dataStructures: ['array'],
    patterns: ['partition-halves'],
  },
  // __PART2__
  // ----- Linked List -----
  {
    id: 'reverse-linked-list',
    title: 'Reverse Linked List',
    slug: 'reverse-linked-list',
    leetcodeUrl: leetCodeUrl('reverse-linked-list'),
    difficulty: 'Easy',
    dataStructures: ['singly-linked-list'],
    patterns: ['three-pointer-reverse'],
  },
  {
    id: 'merge-two-sorted-lists',
    title: 'Merge Two Sorted Lists',
    slug: 'merge-two-sorted-lists',
    leetcodeUrl: leetCodeUrl('merge-two-sorted-lists'),
    difficulty: 'Easy',
    dataStructures: ['singly-linked-list'],
    patterns: ['dummy-head-merge'],
  },
  {
    id: 'reorder-list',
    title: 'Reorder List',
    slug: 'reorder-list',
    leetcodeUrl: leetCodeUrl('reorder-list'),
    difficulty: 'Medium',
    dataStructures: ['singly-linked-list'],
    patterns: ['split-reverse-merge'],
  },
  {
    id: 'remove-nth-node-from-end-of-list',
    title: 'Remove Nth Node From End of List',
    slug: 'remove-nth-node-from-end-of-list',
    leetcodeUrl: leetCodeUrl('remove-nth-node-from-end-of-list'),
    difficulty: 'Medium',
    dataStructures: ['singly-linked-list'],
    patterns: ['two-pointer-gap'],
  },
  {
    id: 'copy-list-with-random-pointer',
    title: 'Copy List with Random Pointer',
    slug: 'copy-list-with-random-pointer',
    leetcodeUrl: leetCodeUrl('copy-list-with-random-pointer'),
    difficulty: 'Medium',
    dataStructures: ['singly-linked-list', 'hash-table'],
    patterns: ['interleave-clone'],
  },
  {
    id: 'add-two-numbers',
    title: 'Add Two Numbers',
    slug: 'add-two-numbers',
    leetcodeUrl: leetCodeUrl('add-two-numbers'),
    difficulty: 'Medium',
    dataStructures: ['singly-linked-list'],
    patterns: ['carry-walk'],
  },
  {
    id: 'linked-list-cycle',
    title: 'Linked List Cycle',
    slug: 'linked-list-cycle',
    leetcodeUrl: leetCodeUrl('linked-list-cycle'),
    difficulty: 'Easy',
    dataStructures: ['singly-linked-list'],
    patterns: ['tortoise-and-hare'],
  },
  {
    id: 'find-the-duplicate-number',
    title: 'Find the Duplicate Number',
    slug: 'find-the-duplicate-number',
    leetcodeUrl: leetCodeUrl('find-the-duplicate-number'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['cycle-detect-values'],
  },
  {
    id: 'lru-cache',
    title: 'LRU Cache',
    slug: 'lru-cache',
    leetcodeUrl: leetCodeUrl('lru-cache'),
    difficulty: 'Medium',
    dataStructures: ['hash-table', 'doubly-linked-list'],
    patterns: ['hash-plus-list'],
  },
  {
    id: 'merge-k-sorted-lists',
    title: 'Merge k Sorted Lists',
    slug: 'merge-k-sorted-lists',
    leetcodeUrl: leetCodeUrl('merge-k-sorted-lists'),
    difficulty: 'Hard',
    dataStructures: ['singly-linked-list', 'heap'],
    patterns: ['heap-merge'],
  },
  {
    id: 'reverse-nodes-in-k-group',
    title: 'Reverse Nodes in k-Group',
    slug: 'reverse-nodes-in-k-group',
    leetcodeUrl: leetCodeUrl('reverse-nodes-in-k-group'),
    difficulty: 'Hard',
    dataStructures: ['singly-linked-list'],
    patterns: ['chunk-reverse'],
  },
  // ----- Trees -----
  {
    id: 'invert-binary-tree',
    title: 'Invert Binary Tree',
    slug: 'invert-binary-tree',
    leetcodeUrl: leetCodeUrl('invert-binary-tree'),
    difficulty: 'Easy',
    dataStructures: ['binary-tree'],
    patterns: ['swap-children-recursion'],
  },
  {
    id: 'maximum-depth-of-binary-tree',
    title: 'Maximum Depth of Binary Tree',
    slug: 'maximum-depth-of-binary-tree',
    leetcodeUrl: leetCodeUrl('maximum-depth-of-binary-tree'),
    difficulty: 'Easy',
    dataStructures: ['binary-tree'],
    patterns: ['recursive-height'],
  },
  {
    id: 'diameter-of-binary-tree',
    title: 'Diameter of Binary Tree',
    slug: 'diameter-of-binary-tree',
    leetcodeUrl: leetCodeUrl('diameter-of-binary-tree'),
    difficulty: 'Easy',
    dataStructures: ['binary-tree'],
    patterns: ['height-plus-path'],
  },
  {
    id: 'balanced-binary-tree',
    title: 'Balanced Binary Tree',
    slug: 'balanced-binary-tree',
    leetcodeUrl: leetCodeUrl('balanced-binary-tree'),
    difficulty: 'Easy',
    dataStructures: ['binary-tree'],
    patterns: ['height-or-unbalanced'],
  },
  {
    id: 'same-tree',
    title: 'Same Tree',
    slug: 'same-tree',
    leetcodeUrl: leetCodeUrl('same-tree'),
    difficulty: 'Easy',
    dataStructures: ['binary-tree'],
    patterns: ['parallel-walk'],
  },
  {
    id: 'subtree-of-another-tree',
    title: 'Subtree of Another Tree',
    slug: 'subtree-of-another-tree',
    leetcodeUrl: leetCodeUrl('subtree-of-another-tree'),
    difficulty: 'Easy',
    dataStructures: ['binary-tree'],
    patterns: ['match-subtrees'],
  },
  {
    id: 'lowest-common-ancestor-of-a-binary-search-tree',
    title: 'Lowest Common Ancestor of a Binary Search Tree',
    slug: 'lowest-common-ancestor-of-a-binary-search-tree',
    leetcodeUrl: leetCodeUrl('lowest-common-ancestor-of-a-binary-search-tree'),
    difficulty: 'Medium',
    dataStructures: ['binary-search-tree', 'binary-tree'],
    patterns: ['guided-walk'],
  },
  {
    id: 'binary-tree-level-order-traversal',
    title: 'Binary Tree Level Order Traversal',
    slug: 'binary-tree-level-order-traversal',
    leetcodeUrl: leetCodeUrl('binary-tree-level-order-traversal'),
    difficulty: 'Medium',
    dataStructures: ['binary-tree', 'queue-deque'],
    patterns: ['wave-snapshot'],
  },
  {
    id: 'binary-tree-right-side-view',
    title: 'Binary Tree Right Side View',
    slug: 'binary-tree-right-side-view',
    leetcodeUrl: leetCodeUrl('binary-tree-right-side-view'),
    difficulty: 'Medium',
    dataStructures: ['binary-tree'],
    patterns: ['last-per-level'],
  },
  {
    id: 'count-good-nodes-in-binary-tree',
    title: 'Count Good Nodes in Binary Tree',
    slug: 'count-good-nodes-in-binary-tree',
    leetcodeUrl: leetCodeUrl('count-good-nodes-in-binary-tree'),
    difficulty: 'Medium',
    dataStructures: ['binary-tree'],
    patterns: ['max-on-path'],
  },
  {
    id: 'validate-binary-search-tree',
    title: 'Validate Binary Search Tree',
    slug: 'validate-binary-search-tree',
    leetcodeUrl: leetCodeUrl('validate-binary-search-tree'),
    difficulty: 'Medium',
    dataStructures: ['binary-search-tree', 'binary-tree'],
    patterns: ['bounds-check-recursion'],
  },
  {
    id: 'kth-smallest-element-in-a-bst',
    title: 'Kth Smallest Element in a BST',
    slug: 'kth-smallest-element-in-a-bst',
    leetcodeUrl: leetCodeUrl('kth-smallest-element-in-a-bst'),
    difficulty: 'Medium',
    dataStructures: ['binary-search-tree', 'binary-tree'],
    patterns: ['inorder-counting'],
  },
  {
    id: 'construct-binary-tree-from-preorder-and-inorder-traversal',
    title: 'Construct Binary Tree from Preorder and Inorder Traversal',
    slug: 'construct-binary-tree-from-preorder-and-inorder-traversal',
    leetcodeUrl: leetCodeUrl('construct-binary-tree-from-preorder-and-inorder-traversal'),
    difficulty: 'Medium',
    dataStructures: ['binary-tree', 'hash-table'],
    patterns: ['root-split-map'],
  },
  {
    id: 'binary-tree-maximum-path-sum',
    title: 'Binary Tree Maximum Path Sum',
    slug: 'binary-tree-maximum-path-sum',
    leetcodeUrl: leetCodeUrl('binary-tree-maximum-path-sum'),
    difficulty: 'Hard',
    dataStructures: ['binary-tree'],
    patterns: ['gain-or-drop'],
  },
  {
    id: 'serialize-and-deserialize-binary-tree',
    title: 'Serialize and Deserialize Binary Tree',
    slug: 'serialize-and-deserialize-binary-tree',
    leetcodeUrl: leetCodeUrl('serialize-and-deserialize-binary-tree'),
    difficulty: 'Hard',
    dataStructures: ['binary-tree'],
    patterns: ['preorder-with-nulls'],
  },
  // ----- Heap / Priority Queue -----
  {
    id: 'kth-largest-element-in-a-stream',
    title: 'Kth Largest Element in a Stream',
    slug: 'kth-largest-element-in-a-stream',
    leetcodeUrl: leetCodeUrl('kth-largest-element-in-a-stream'),
    difficulty: 'Easy',
    dataStructures: ['heap'],
    patterns: ['size-k-min-heap'],
  },
  {
    id: 'last-stone-weight',
    title: 'Last Stone Weight',
    slug: 'last-stone-weight',
    leetcodeUrl: leetCodeUrl('last-stone-weight'),
    difficulty: 'Easy',
    dataStructures: ['heap'],
    patterns: ['max-heap-simulation'],
  },
  {
    id: 'k-closest-points-to-origin',
    title: 'K Closest Points to Origin',
    slug: 'k-closest-points-to-origin',
    leetcodeUrl: leetCodeUrl('k-closest-points-to-origin'),
    difficulty: 'Medium',
    dataStructures: ['heap'],
    patterns: ['max-heap-of-k'],
  },
  {
    id: 'kth-largest-element-in-an-array',
    title: 'Kth Largest Element in an Array',
    slug: 'kth-largest-element-in-an-array',
    leetcodeUrl: leetCodeUrl('kth-largest-element-in-an-array'),
    difficulty: 'Medium',
    dataStructures: ['heap', 'array'],
    patterns: ['size-k-min-heap'],
  },
  {
    id: 'task-scheduler',
    title: 'Task Scheduler',
    slug: 'task-scheduler',
    leetcodeUrl: leetCodeUrl('task-scheduler'),
    difficulty: 'Medium',
    dataStructures: ['heap', 'queue-deque'],
    patterns: ['cooldown-counts'],
  },
  {
    id: 'design-twitter',
    title: 'Design Twitter',
    slug: 'design-twitter',
    leetcodeUrl: leetCodeUrl('design-twitter'),
    difficulty: 'Medium',
    dataStructures: ['heap', 'hash-table'],
    patterns: ['merge-feeds'],
  },
  {
    id: 'find-median-from-data-stream',
    title: 'Find Median from Data Stream',
    slug: 'find-median-from-data-stream',
    leetcodeUrl: leetCodeUrl('find-median-from-data-stream'),
    difficulty: 'Hard',
    dataStructures: ['heap'],
    patterns: ['two-heap-balance'],
  },
  // ----- Backtracking -----
  {
    id: 'subsets',
    title: 'Subsets',
    slug: 'subsets',
    leetcodeUrl: leetCodeUrl('subsets'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['include-exclude'],
  },
  {
    id: 'combination-sum',
    title: 'Combination Sum',
    slug: 'combination-sum',
    leetcodeUrl: leetCodeUrl('combination-sum'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['reuse-branch-dfs'],
  },
  {
    id: 'combination-sum-ii',
    title: 'Combination Sum II',
    slug: 'combination-sum-ii',
    leetcodeUrl: leetCodeUrl('combination-sum-ii'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['sorted-skip-dups'],
  },
  {
    id: 'permutations',
    title: 'Permutations',
    slug: 'permutations',
    leetcodeUrl: leetCodeUrl('permutations'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['used-set-dfs'],
  },
  {
    id: 'subsets-ii',
    title: 'Subsets II',
    slug: 'subsets-ii',
    leetcodeUrl: leetCodeUrl('subsets-ii'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['sorted-skip-dups'],
  },
  {
    id: 'word-search',
    title: 'Word Search',
    slug: 'word-search',
    leetcodeUrl: leetCodeUrl('word-search'),
    difficulty: 'Medium',
    dataStructures: ['matrix'],
    patterns: ['dfs-mark-restore'],
  },
  {
    id: 'palindrome-partitioning',
    title: 'Palindrome Partitioning',
    slug: 'palindrome-partitioning',
    leetcodeUrl: leetCodeUrl('palindrome-partitioning'),
    difficulty: 'Medium',
    dataStructures: ['string'],
    patterns: ['palindrome-prefix-dfs'],
  },
  {
    id: 'letter-combinations-of-a-phone-number',
    title: 'Letter Combinations of a Phone Number',
    slug: 'letter-combinations-of-a-phone-number',
    leetcodeUrl: leetCodeUrl('letter-combinations-of-a-phone-number'),
    difficulty: 'Medium',
    dataStructures: ['string'],
    patterns: ['digit-branch-dfs'],
  },
  {
    id: 'n-queens',
    title: 'N-Queens',
    slug: 'n-queens',
    leetcodeUrl: leetCodeUrl('n-queens'),
    difficulty: 'Hard',
    dataStructures: ['matrix'],
    patterns: ['column-diag-sets'],
  },
  // ----- Tries -----
  {
    id: 'implement-trie-prefix-tree',
    title: 'Implement Trie (Prefix Tree)',
    slug: 'implement-trie-prefix-tree',
    leetcodeUrl: leetCodeUrl('implement-trie-prefix-tree'),
    difficulty: 'Medium',
    dataStructures: ['trie'],
    patterns: ['map-children-trie'],
  },
  {
    id: 'design-add-and-search-words-data-structure',
    title: 'Design Add and Search Words Data Structure',
    slug: 'design-add-and-search-words-data-structure',
    leetcodeUrl: leetCodeUrl('design-add-and-search-words-data-structure'),
    difficulty: 'Medium',
    dataStructures: ['trie'],
    patterns: ['wildcard-dfs-trie'],
  },
  {
    id: 'word-search-ii',
    title: 'Word Search II',
    slug: 'word-search-ii',
    leetcodeUrl: leetCodeUrl('word-search-ii'),
    difficulty: 'Hard',
    dataStructures: ['trie', 'matrix'],
    patterns: ['trie-pruned-dfs'],
  },
  // ----- Graphs -----
  {
    id: 'number-of-islands',
    title: 'Number of Islands',
    slug: 'number-of-islands',
    leetcodeUrl: leetCodeUrl('number-of-islands'),
    difficulty: 'Medium',
    dataStructures: ['graph-representations'],
    patterns: ['grid-dfs-flood'],
  },
  {
    id: 'max-area-of-island',
    title: 'Max Area of Island',
    slug: 'max-area-of-island',
    leetcodeUrl: leetCodeUrl('max-area-of-island'),
    difficulty: 'Medium',
    dataStructures: ['graph-representations'],
    patterns: ['grid-dfs-area'],
  },
  {
    id: 'clone-graph',
    title: 'Clone Graph',
    slug: 'clone-graph',
    leetcodeUrl: leetCodeUrl('clone-graph'),
    difficulty: 'Medium',
    dataStructures: ['hash-table'],
    patterns: ['dfs-copy-map'],
  },
  {
    id: 'walls-and-gates',
    title: 'Walls and Gates',
    slug: 'walls-and-gates',
    leetcodeUrl: leetCodeUrl('walls-and-gates'),
    difficulty: 'Medium',
    dataStructures: ['graph-representations', 'matrix'],
    patterns: ['multi-source-bfs'],
  },
  {
    id: 'rotting-oranges',
    title: 'Rotting Oranges',
    slug: 'rotting-oranges',
    leetcodeUrl: leetCodeUrl('rotting-oranges'),
    difficulty: 'Medium',
    dataStructures: ['queue-deque'],
    patterns: ['multi-source-bfs'],
  },
  {
    id: 'pacific-atlantic-water-flow',
    title: 'Pacific Atlantic Water Flow',
    slug: 'pacific-atlantic-water-flow',
    leetcodeUrl: leetCodeUrl('pacific-atlantic-water-flow'),
    difficulty: 'Medium',
    dataStructures: ['graph-representations'],
    patterns: ['reverse-shore-dfs'],
  },
  {
    id: 'surrounded-regions',
    title: 'Surrounded Regions',
    slug: 'surrounded-regions',
    leetcodeUrl: leetCodeUrl('surrounded-regions'),
    difficulty: 'Medium',
    dataStructures: ['matrix'],
    patterns: ['border-dfs-mark'],
  },
  {
    id: 'number-of-connected-components-in-an-undirected-graph',
    title: 'Number of Connected Components in an Undirected Graph',
    slug: 'number-of-connected-components-in-an-undirected-graph',
    leetcodeUrl: leetCodeUrl('number-of-connected-components-in-an-undirected-graph'),
    difficulty: 'Medium',
    dataStructures: ['union-find'],
    patterns: ['union-all-edges'],
  },
  {
    id: 'graph-valid-tree',
    title: 'Graph Valid Tree',
    slug: 'graph-valid-tree',
    leetcodeUrl: leetCodeUrl('graph-valid-tree'),
    difficulty: 'Medium',
    dataStructures: ['union-find'],
    patterns: ['edges-equals-vertices-minus-one'],
  },
  {
    id: 'word-ladder',
    title: 'Word Ladder',
    slug: 'word-ladder',
    leetcodeUrl: leetCodeUrl('word-ladder'),
    difficulty: 'Hard',
    dataStructures: ['queue-deque', 'hash-set'],
    patterns: ['implicit-graph-bfs'],
  },
  {
    id: 'course-schedule',
    title: 'Course Schedule',
    slug: 'course-schedule',
    leetcodeUrl: leetCodeUrl('course-schedule'),
    difficulty: 'Medium',
    dataStructures: ['advanced-graphs'],
    patterns: ['cycle-detect-directed'],
  },
  {
    id: 'course-schedule-ii',
    title: 'Course Schedule II',
    slug: 'course-schedule-ii',
    leetcodeUrl: leetCodeUrl('course-schedule-ii'),
    difficulty: 'Medium',
    dataStructures: ['advanced-graphs'],
    patterns: ['kahns-topo-order'],
  },
  {
    id: 'redundant-connection',
    title: 'Redundant Connection',
    slug: 'redundant-connection',
    leetcodeUrl: leetCodeUrl('redundant-connection'),
    difficulty: 'Medium',
    dataStructures: ['union-find'],
    patterns: ['first-cycle-edge'],
  },
  // __PART3__
  // ----- 1-D DP -----
  {
    id: 'climbing-stairs',
    title: 'Climbing Stairs',
    slug: 'climbing-stairs',
    leetcodeUrl: leetCodeUrl('climbing-stairs'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['fib-like-dp'],
  },
  {
    id: 'min-cost-climbing-stairs',
    title: 'Min Cost Climbing Stairs',
    slug: 'min-cost-climbing-stairs',
    leetcodeUrl: leetCodeUrl('min-cost-climbing-stairs'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['min-step-dp'],
  },
  {
    id: 'house-robber',
    title: 'House Robber',
    slug: 'house-robber',
    leetcodeUrl: leetCodeUrl('house-robber'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['skip-or-take-dp'],
  },
  {
    id: 'house-robber-ii',
    title: 'House Robber II',
    slug: 'house-robber-ii',
    leetcodeUrl: leetCodeUrl('house-robber-ii'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['two-case-dp'],
  },
  {
    id: 'longest-palindromic-substring',
    title: 'Longest Palindromic Substring',
    slug: 'longest-palindromic-substring',
    leetcodeUrl: leetCodeUrl('longest-palindromic-substring'),
    difficulty: 'Medium',
    dataStructures: ['string'],
    patterns: ['expand-centers'],
  },
  {
    id: 'palindromic-substrings',
    title: 'Palindromic Substrings',
    slug: 'palindromic-substrings',
    leetcodeUrl: leetCodeUrl('palindromic-substrings'),
    difficulty: 'Medium',
    dataStructures: ['string'],
    patterns: ['expand-centers'],
  },
  {
    id: 'decode-ways',
    title: 'Decode Ways',
    slug: 'decode-ways',
    leetcodeUrl: leetCodeUrl('decode-ways'),
    difficulty: 'Medium',
    dataStructures: ['string'],
    patterns: ['one-two-step-dp'],
  },
  {
    id: 'coin-change',
    title: 'Coin Change',
    slug: 'coin-change',
    leetcodeUrl: leetCodeUrl('coin-change'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['min-over-coins'],
  },
  {
    id: 'maximum-product-subarray',
    title: 'Maximum Product Subarray',
    slug: 'maximum-product-subarray',
    leetcodeUrl: leetCodeUrl('maximum-product-subarray'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['track-min-max'],
  },
  {
    id: 'word-break',
    title: 'Word Break',
    slug: 'word-break',
    leetcodeUrl: leetCodeUrl('word-break'),
    difficulty: 'Medium',
    dataStructures: ['string'],
    patterns: ['prefix-reachable'],
  },
  {
    id: 'longest-increasing-subsequence',
    title: 'Longest Increasing Subsequence',
    slug: 'longest-increasing-subsequence',
    leetcodeUrl: leetCodeUrl('longest-increasing-subsequence'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['patience-or-dp'],
  },
  {
    id: 'partition-equal-subset-sum',
    title: 'Partition Equal Subset Sum',
    slug: 'partition-equal-subset-sum',
    leetcodeUrl: leetCodeUrl('partition-equal-subset-sum'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['half-sum-subset'],
  },
  // ----- 2-D DP -----
  {
    id: 'unique-paths',
    title: 'Unique Paths',
    slug: 'unique-paths',
    leetcodeUrl: leetCodeUrl('unique-paths'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['grid-combine'],
  },
  {
    id: 'longest-common-subsequence',
    title: 'Longest Common Subsequence',
    slug: 'longest-common-subsequence',
    leetcodeUrl: leetCodeUrl('longest-common-subsequence'),
    difficulty: 'Medium',
    dataStructures: ['string'],
    patterns: ['diagonal-match-dp'],
  },
  {
    id: 'best-time-to-buy-and-sell-stock-with-cooldown',
    title: 'Best Time to Buy and Sell Stock with Cooldown',
    slug: 'best-time-to-buy-and-sell-stock-with-cooldown',
    leetcodeUrl: leetCodeUrl('best-time-to-buy-and-sell-stock-with-cooldown'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['state-machine-dp'],
  },
  {
    id: 'coin-change-ii',
    title: 'Coin Change II',
    slug: 'coin-change-ii',
    leetcodeUrl: leetCodeUrl('coin-change-ii'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['unbounded-count-dp'],
  },
  {
    id: 'target-sum',
    title: 'Target Sum',
    slug: 'target-sum',
    leetcodeUrl: leetCodeUrl('target-sum'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['subset-transform'],
  },
  {
    id: 'interleaving-string',
    title: 'Interleaving String',
    slug: 'interleaving-string',
    leetcodeUrl: leetCodeUrl('interleaving-string'),
    difficulty: 'Medium',
    dataStructures: ['string'],
    patterns: ['grid-match-dp'],
  },
  {
    id: 'longest-increasing-path-in-a-matrix',
    title: 'Longest Increasing Path in a Matrix',
    slug: 'longest-increasing-path-in-a-matrix',
    leetcodeUrl: leetCodeUrl('longest-increasing-path-in-a-matrix'),
    difficulty: 'Hard',
    dataStructures: ['matrix'],
    patterns: ['dfs-memo-grid'],
  },
  {
    id: 'distinct-subsequences',
    title: 'Distinct Subsequences',
    slug: 'distinct-subsequences',
    leetcodeUrl: leetCodeUrl('distinct-subsequences'),
    difficulty: 'Hard',
    dataStructures: ['string'],
    patterns: ['match-skip-dp'],
  },
  {
    id: 'edit-distance',
    title: 'Edit Distance',
    slug: 'edit-distance',
    leetcodeUrl: leetCodeUrl('edit-distance'),
    difficulty: 'Hard',
    dataStructures: ['string'],
    patterns: ['three-neighbor-dp'],
  },
  {
    id: 'burst-balloons',
    title: 'Burst Balloons',
    slug: 'burst-balloons',
    leetcodeUrl: leetCodeUrl('burst-balloons'),
    difficulty: 'Hard',
    dataStructures: ['array'],
    patterns: ['last-burst-interval'],
  },
  {
    id: 'regular-expression-matching',
    title: 'Regular Expression Matching',
    slug: 'regular-expression-matching',
    leetcodeUrl: leetCodeUrl('regular-expression-matching'),
    difficulty: 'Hard',
    dataStructures: ['string'],
    patterns: ['star-branch-dp'],
  },
  // ----- Greedy -----
  {
    id: 'maximum-subarray',
    title: 'Maximum Subarray',
    slug: 'maximum-subarray',
    leetcodeUrl: leetCodeUrl('maximum-subarray'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['kadane-scan'],
  },
  {
    id: 'jump-game',
    title: 'Jump Game',
    slug: 'jump-game',
    leetcodeUrl: leetCodeUrl('jump-game'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['reach-tracking'],
  },
  {
    id: 'jump-game-ii',
    title: 'Jump Game II',
    slug: 'jump-game-ii',
    leetcodeUrl: leetCodeUrl('jump-game-ii'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['jump-on-exhaustion'],
  },
  {
    id: 'gas-station',
    title: 'Gas Station',
    slug: 'gas-station',
    leetcodeUrl: leetCodeUrl('gas-station'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['restart-on-deficit'],
  },
  {
    id: 'hand-of-straights',
    title: 'Hand of Straights',
    slug: 'hand-of-straights',
    leetcodeUrl: leetCodeUrl('hand-of-straights'),
    difficulty: 'Medium',
    dataStructures: ['hash-table', 'sorting'],
    patterns: ['consecutive-groups'],
  },
  {
    id: 'merge-triplets-to-form-target-triplet',
    title: 'Merge Triplets to Form Target Triplet',
    slug: 'merge-triplets-to-form-target-triplet',
    leetcodeUrl: leetCodeUrl('merge-triplets-to-form-target-triplet'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['max-per-column'],
  },
  {
    id: 'partition-labels',
    title: 'Partition Labels',
    slug: 'partition-labels',
    leetcodeUrl: leetCodeUrl('partition-labels'),
    difficulty: 'Medium',
    dataStructures: ['string', 'hash-table'],
    patterns: ['last-occurrence-cut'],
  },
  {
    id: 'valid-parenthesis-string',
    title: 'Valid Parenthesis String',
    slug: 'valid-parenthesis-string',
    leetcodeUrl: leetCodeUrl('valid-parenthesis-string'),
    difficulty: 'Medium',
    dataStructures: ['string', 'stack'],
    patterns: ['low-high-balance'],
  },
  // ----- Intervals -----
  {
    id: 'insert-interval',
    title: 'Insert Interval',
    slug: 'insert-interval',
    leetcodeUrl: leetCodeUrl('insert-interval'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['splice-sweep'],
  },
  {
    id: 'merge-intervals',
    title: 'Merge Intervals',
    slug: 'merge-intervals',
    leetcodeUrl: leetCodeUrl('merge-intervals'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['sort-then-sweep'],
  },
  {
    id: 'non-overlapping-intervals',
    title: 'Non-overlapping Intervals',
    slug: 'non-overlapping-intervals',
    leetcodeUrl: leetCodeUrl('non-overlapping-intervals'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['earliest-finish-greedy'],
  },
  {
    id: 'meeting-rooms',
    title: 'Meeting Rooms',
    slug: 'meeting-rooms',
    leetcodeUrl: leetCodeUrl('meeting-rooms'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['sort-then-scan'],
  },
  {
    id: 'meeting-rooms-ii',
    title: 'Meeting Rooms II',
    slug: 'meeting-rooms-ii',
    leetcodeUrl: leetCodeUrl('meeting-rooms-ii'),
    difficulty: 'Medium',
    dataStructures: ['array', 'heap'],
    patterns: ['min-heap-rooms'],
  },
  {
    id: 'minimum-interval-to-include-each-query',
    title: 'Minimum Interval to Include Each Query',
    slug: 'minimum-interval-to-include-each-query',
    leetcodeUrl: leetCodeUrl('minimum-interval-to-include-each-query'),
    difficulty: 'Hard',
    dataStructures: ['array', 'sorting'],
    patterns: ['sweep-with-heap'],
  },
  // ----- Math & Geometry -----
  {
    id: 'rotate-image',
    title: 'Rotate Image',
    slug: 'rotate-image',
    leetcodeUrl: leetCodeUrl('rotate-image'),
    difficulty: 'Medium',
    dataStructures: ['matrix'],
    patterns: ['transpose-reverse'],
  },
  {
    id: 'spiral-matrix',
    title: 'Spiral Matrix',
    slug: 'spiral-matrix',
    leetcodeUrl: leetCodeUrl('spiral-matrix'),
    difficulty: 'Medium',
    dataStructures: ['matrix'],
    patterns: ['layer-walk'],
  },
  {
    id: 'set-matrix-zeroes',
    title: 'Set Matrix Zeroes',
    slug: 'set-matrix-zeroes',
    leetcodeUrl: leetCodeUrl('set-matrix-zeroes'),
    difficulty: 'Medium',
    dataStructures: ['matrix'],
    patterns: ['first-row-col-markers'],
  },
  {
    id: 'happy-number',
    title: 'Happy Number',
    slug: 'happy-number',
    leetcodeUrl: leetCodeUrl('happy-number'),
    difficulty: 'Easy',
    dataStructures: ['hash-set', 'singly-linked-list'],
    patterns: ['seen-set-cycle'],
  },
  {
    id: 'plus-one',
    title: 'Plus One',
    slug: 'plus-one',
    leetcodeUrl: leetCodeUrl('plus-one'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['carry-walk'],
  },
  {
    id: 'powx-n',
    title: 'Pow(x, n)',
    slug: 'powx-n',
    leetcodeUrl: leetCodeUrl('powx-n'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['halving-recursion'],
  },
  {
    id: 'multiply-strings',
    title: 'Multiply Strings',
    slug: 'multiply-strings',
    leetcodeUrl: leetCodeUrl('multiply-strings'),
    difficulty: 'Medium',
    dataStructures: ['string'],
    patterns: ['grade-school-pos'],
  },
  {
    id: 'detect-squares',
    title: 'Detect Squares',
    slug: 'detect-squares',
    leetcodeUrl: leetCodeUrl('detect-squares'),
    difficulty: 'Medium',
    dataStructures: ['hash-table'],
    patterns: ['pair-count-corners'],
  },
  // ----- Bit Manipulation -----
  {
    id: 'single-number',
    title: 'Single Number',
    slug: 'single-number',
    leetcodeUrl: leetCodeUrl('single-number'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['xor-cancel'],
  },
  {
    id: 'number-of-1-bits',
    title: 'Number of 1 Bits',
    slug: 'number-of-1-bits',
    leetcodeUrl: leetCodeUrl('number-of-1-bits'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['lowbit-peel'],
  },
  {
    id: 'counting-bits',
    title: 'Counting Bits',
    slug: 'counting-bits',
    leetcodeUrl: leetCodeUrl('counting-bits'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['dp-lowbit'],
  },
  {
    id: 'reverse-bits',
    title: 'Reverse Bits',
    slug: 'reverse-bits',
    leetcodeUrl: leetCodeUrl('reverse-bits'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['bit-mirror-loop'],
  },
  {
    id: 'missing-number',
    title: 'Missing Number',
    slug: 'missing-number',
    leetcodeUrl: leetCodeUrl('missing-number'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['linear-scan'],
  },
  {
    id: 'sum-of-two-integers',
    title: 'Sum of Two Integers',
    slug: 'sum-of-two-integers',
    leetcodeUrl: leetCodeUrl('sum-of-two-integers'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['carry-xor-loop'],
  },
  {
    id: 'reverse-integer',
    title: 'Reverse Integer',
    slug: 'reverse-integer',
    leetcodeUrl: leetCodeUrl('reverse-integer'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['pop-push-overflow'],
  },
  // ----- Advanced Graphs -----
  {
    id: 'reconstruct-itinerary',
    title: 'Reconstruct Itinerary',
    slug: 'reconstruct-itinerary',
    leetcodeUrl: leetCodeUrl('reconstruct-itinerary'),
    difficulty: 'Hard',
    dataStructures: ['advanced-graphs'],
    patterns: ['hierholzer-euler'],
  },
  {
    id: 'min-cost-to-connect-all-points',
    title: 'Min Cost to Connect All Points',
    slug: 'min-cost-to-connect-all-points',
    leetcodeUrl: leetCodeUrl('min-cost-to-connect-all-points'),
    difficulty: 'Medium',
    dataStructures: ['weighted-graph', 'union-find'],
    patterns: ['complete-graph-mst'],
  },
  {
    id: 'network-delay-time',
    title: 'Network Delay Time',
    slug: 'network-delay-time',
    leetcodeUrl: leetCodeUrl('network-delay-time'),
    difficulty: 'Medium',
    dataStructures: ['weighted-graph', 'heap'],
    patterns: ['dijkstra-source'],
  },
  {
    id: 'swimming-in-rising-water',
    title: 'Swimming in Rising Water',
    slug: 'swimming-in-rising-water',
    leetcodeUrl: leetCodeUrl('swimming-in-rising-water'),
    difficulty: 'Hard',
    dataStructures: ['weighted-graph', 'heap'],
    patterns: ['bottleneck-dijkstra'],
  },
  {
    id: 'alien-dictionary',
    title: 'Alien Dictionary',
    slug: 'alien-dictionary',
    leetcodeUrl: leetCodeUrl('alien-dictionary'),
    difficulty: 'Hard',
    dataStructures: ['advanced-graphs'],
    patterns: ['topo-char-order'],
  },
  {
    id: 'cheapest-flights-within-k-stops',
    title: 'Cheapest Flights Within K Stops',
    slug: 'cheapest-flights-within-k-stops',
    leetcodeUrl: leetCodeUrl('cheapest-flights-within-k-stops'),
    difficulty: 'Medium',
    dataStructures: ['weighted-graph'],
    patterns: ['bounded-bellman-ford'],
  },
  // ----- Extras -----
  {
    id: 'move-zeroes',
    title: 'Move Zeroes',
    slug: 'move-zeroes',
    leetcodeUrl: leetCodeUrl('move-zeroes'),
    difficulty: 'Easy',
    dataStructures: ['array', 'dynamic-array'],
    patterns: ['two-pointers-compact'],
  },
  {
    id: 'remove-duplicates-from-sorted-array',
    title: 'Remove Duplicates from Sorted Array',
    slug: 'remove-duplicates-from-sorted-array',
    leetcodeUrl: leetCodeUrl('remove-duplicates-from-sorted-array'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['slow-fast-write'],
  },
  {
    id: 'majority-element',
    title: 'Majority Element',
    slug: 'majority-element',
    leetcodeUrl: leetCodeUrl('majority-element'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['boyer-moore-vote'],
  },
];
