import type { Problem } from '../../types/content.ts';
import { leetCodeUrl } from '../../types/content.ts';

/** Starter practice problems referenced by early topics. All slugs are real. */
export const starterProblems: Problem[] = [
  {
    id: 'two-sum',
    title: 'Two Sum',
    slug: 'two-sum',
    leetcodeUrl: leetCodeUrl('two-sum'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table'],
    patterns: ['hash-map-complement'],
  },
  {
    id: 'contains-duplicate',
    title: 'Contains Duplicate',
    slug: 'contains-duplicate',
    leetcodeUrl: leetCodeUrl('contains-duplicate'),
    difficulty: 'Easy',
    dataStructures: ['array', 'hash-table', 'sorting'],
    patterns: ['seen-set'],
  },
  {
    id: 'best-time-to-buy-and-sell-stock',
    title: 'Best Time to Buy and Sell Stock',
    slug: 'best-time-to-buy-and-sell-stock',
    leetcodeUrl: leetCodeUrl('best-time-to-buy-and-sell-stock'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['one-pass-min-tracking'],
  },
  {
    id: 'merge-sorted-array',
    title: 'Merge Sorted Array',
    slug: 'merge-sorted-array',
    leetcodeUrl: leetCodeUrl('merge-sorted-array'),
    difficulty: 'Easy',
    dataStructures: ['array', 'dynamic-array'],
    patterns: ['two-pointers-backwards'],
  },
  {
    id: 'move-zeroes',
    title: 'Move Zeroes',
    slug: 'move-zeroes',
    leetcodeUrl: leetCodeUrl('move-zeroes'),
    difficulty: 'Easy',
    dataStructures: ['array', 'dynamic-array'],
    patterns: ['two-pointers-compact'],
  },
  {
    id: 'valid-anagram',
    title: 'Valid Anagram',
    slug: 'valid-anagram',
    leetcodeUrl: leetCodeUrl('valid-anagram'),
    difficulty: 'Easy',
    dataStructures: ['string', 'hash-table'],
    patterns: ['frequency-count'],
  },
  {
    id: 'valid-palindrome',
    title: 'Valid Palindrome',
    slug: 'valid-palindrome',
    leetcodeUrl: leetCodeUrl('valid-palindrome'),
    difficulty: 'Easy',
    dataStructures: ['string'],
    patterns: ['two-pointers-inward'],
  },
  {
    id: 'reverse-linked-list',
    title: 'Reverse Linked List',
    slug: 'reverse-linked-list',
    leetcodeUrl: leetCodeUrl('reverse-linked-list'),
    difficulty: 'Easy',
    dataStructures: ['singly-linked-list'],
    patterns: ['three-pointer-reverse'],
  },
  {
    id: 'merge-two-sorted-lists',
    title: 'Merge Two Sorted Lists',
    slug: 'merge-two-sorted-lists',
    leetcodeUrl: leetCodeUrl('merge-two-sorted-lists'),
    difficulty: 'Easy',
    dataStructures: ['singly-linked-list'],
    patterns: ['dummy-head-merge'],
  },
  {
    id: 'linked-list-cycle',
    title: 'Linked List Cycle',
    slug: 'linked-list-cycle',
    leetcodeUrl: leetCodeUrl('linked-list-cycle'),
    difficulty: 'Easy',
    dataStructures: ['singly-linked-list'],
    patterns: ['tortoise-and-hare'],
  },
  {
    id: 'design-linked-list',
    title: 'Design Linked List',
    slug: 'design-linked-list',
    leetcodeUrl: leetCodeUrl('design-linked-list'),
    difficulty: 'Medium',
    dataStructures: ['singly-linked-list', 'doubly-linked-list'],
    patterns: ['sentinel-node'],
  },
  {
    id: 'design-browser-history',
    title: 'Design Browser History',
    slug: 'design-browser-history',
    leetcodeUrl: leetCodeUrl('design-browser-history'),
    difficulty: 'Medium',
    dataStructures: ['doubly-linked-list', 'stack'],
    patterns: ['two-stacks-cursor'],
  },
  {
    id: 'valid-parentheses',
    title: 'Valid Parentheses',
    slug: 'valid-parentheses',
    leetcodeUrl: leetCodeUrl('valid-parentheses'),
    difficulty: 'Easy',
    dataStructures: ['stack', 'string'],
    patterns: ['push-openers'],
  },
  {
    id: 'min-stack',
    title: 'Min Stack',
    slug: 'min-stack',
    leetcodeUrl: leetCodeUrl('min-stack'),
    difficulty: 'Medium',
    dataStructures: ['stack'],
    patterns: ['auxiliary-min-stack'],
  },
  {
    id: 'implement-queue-using-stacks',
    title: 'Implement Queue using Stacks',
    slug: 'implement-queue-using-stacks',
    leetcodeUrl: leetCodeUrl('implement-queue-using-stacks'),
    difficulty: 'Easy',
    dataStructures: ['queue-deque', 'stack'],
    patterns: ['two-stack-transfer'],
  },
  {
    id: 'number-of-recent-calls',
    title: 'Number of Recent Calls',
    slug: 'number-of-recent-calls',
    leetcodeUrl: leetCodeUrl('number-of-recent-calls'),
    difficulty: 'Easy',
    dataStructures: ['queue-deque'],
    patterns: ['sliding-window-queue'],
  },
  {
    id: 'group-anagrams',
    title: 'Group Anagrams',
    slug: 'group-anagrams',
    leetcodeUrl: leetCodeUrl('group-anagrams'),
    difficulty: 'Medium',
    dataStructures: ['hash-table', 'string'],
    patterns: ['sorted-key-grouping'],
  },
  {
    id: 'longest-substring-without-repeating-characters',
    title: 'Longest Substring Without Repeating Characters',
    slug: 'longest-substring-without-repeating-characters',
    leetcodeUrl: leetCodeUrl('longest-substring-without-repeating-characters'),
    difficulty: 'Medium',
    dataStructures: ['hash-table', 'string'],
    patterns: ['sliding-window-last-seen'],
  },
  {
    id: 'happy-number',
    title: 'Happy Number',
    slug: 'happy-number',
    leetcodeUrl: leetCodeUrl('happy-number'),
    difficulty: 'Easy',
    dataStructures: ['hash-set', 'singly-linked-list'],
    patterns: ['seen-set-cycle'],
  },
  {
    id: 'intersection-of-two-arrays',
    title: 'Intersection of Two Arrays',
    slug: 'intersection-of-two-arrays',
    leetcodeUrl: leetCodeUrl('intersection-of-two-arrays'),
    difficulty: 'Easy',
    dataStructures: ['hash-set', 'array'],
    patterns: ['membership-filter'],
  },
  {
    id: 'maximum-depth-of-binary-tree',
    title: 'Maximum Depth of Binary Tree',
    slug: 'maximum-depth-of-binary-tree',
    leetcodeUrl: leetCodeUrl('maximum-depth-of-binary-tree'),
    difficulty: 'Easy',
    dataStructures: ['binary-tree'],
    patterns: ['recursive-height'],
  },
  {
    id: 'invert-binary-tree',
    title: 'Invert Binary Tree',
    slug: 'invert-binary-tree',
    leetcodeUrl: leetCodeUrl('invert-binary-tree'),
    difficulty: 'Easy',
    dataStructures: ['binary-tree'],
    patterns: ['swap-children-recursion'],
  },
  {
    id: 'binary-tree-inorder-traversal',
    title: 'Binary Tree Inorder Traversal',
    slug: 'binary-tree-inorder-traversal',
    leetcodeUrl: leetCodeUrl('binary-tree-inorder-traversal'),
    difficulty: 'Easy',
    dataStructures: ['binary-tree'],
    patterns: ['inorder-walk'],
  },
  {
    id: 'validate-binary-search-tree',
    title: 'Validate Binary Search Tree',
    slug: 'validate-binary-search-tree',
    leetcodeUrl: leetCodeUrl('validate-binary-search-tree'),
    difficulty: 'Medium',
    dataStructures: ['binary-search-tree', 'binary-tree'],
    patterns: ['bounds-check-recursion'],
  },
  {
    id: 'lowest-common-ancestor-of-a-binary-search-tree',
    title: 'Lowest Common Ancestor of a Binary Search Tree',
    slug: 'lowest-common-ancestor-of-a-binary-search-tree',
    leetcodeUrl: leetCodeUrl('lowest-common-ancestor-of-a-binary-search-tree'),
    difficulty: 'Easy',
    dataStructures: ['binary-search-tree', 'binary-tree'],
    patterns: ['guided-walk'],
  },
  {
    id: 'kth-smallest-element-in-a-bst',
    title: 'Kth Smallest Element in a BST',
    slug: 'kth-smallest-element-in-a-bst',
    leetcodeUrl: leetCodeUrl('kth-smallest-element-in-a-bst'),
    difficulty: 'Medium',
    dataStructures: ['binary-search-tree', 'binary-tree'],
    patterns: ['inorder-counting'],
  },
  {
    id: 'kth-largest-element-in-an-array',
    title: 'Kth Largest Element in an Array',
    slug: 'kth-largest-element-in-an-array',
    leetcodeUrl: leetCodeUrl('kth-largest-element-in-an-array'),
    difficulty: 'Medium',
    dataStructures: ['heap', 'array'],
    patterns: ['size-k-min-heap'],
  },
  {
    id: 'last-stone-weight',
    title: 'Last Stone Weight',
    slug: 'last-stone-weight',
    leetcodeUrl: leetCodeUrl('last-stone-weight'),
    difficulty: 'Easy',
    dataStructures: ['heap'],
    patterns: ['max-heap-simulation'],
  },
  {
    id: 'top-k-frequent-elements',
    title: 'Top K Frequent Elements',
    slug: 'top-k-frequent-elements',
    leetcodeUrl: leetCodeUrl('top-k-frequent-elements'),
    difficulty: 'Medium',
    dataStructures: ['heap', 'hash-table'],
    patterns: ['heap-plus-frequency-map'],
  },
  {
    id: 'implement-trie-prefix-tree',
    title: 'Implement Trie (Prefix Tree)',
    slug: 'implement-trie-prefix-tree',
    leetcodeUrl: leetCodeUrl('implement-trie-prefix-tree'),
    difficulty: 'Medium',
    dataStructures: ['trie'],
    patterns: ['map-children-trie'],
  },
  {
    id: 'design-add-and-search-words-data-structure',
    title: 'Design Add and Search Words Data Structure',
    slug: 'design-add-and-search-words-data-structure',
    leetcodeUrl: leetCodeUrl('design-add-and-search-words-data-structure'),
    difficulty: 'Medium',
    dataStructures: ['trie'],
    patterns: ['wildcard-dfs-trie'],
  },
  {
    id: 'range-sum-query-mutable',
    title: 'Range Sum Query - Mutable',
    slug: 'range-sum-query-mutable',
    leetcodeUrl: leetCodeUrl('range-sum-query-mutable'),
    difficulty: 'Medium',
    dataStructures: ['segment-tree', 'fenwick-tree', 'array'],
    patterns: ['range-aggregate-tree'],
  },
  {
    id: 'range-sum-query-immutable',
    title: 'Range Sum Query - Immutable',
    slug: 'range-sum-query-immutable',
    leetcodeUrl: leetCodeUrl('range-sum-query-immutable'),
    difficulty: 'Easy',
    dataStructures: ['array', 'segment-tree'],
    patterns: ['prefix-sums'],
  },
  {
    id: 'count-of-smaller-numbers-after-self',
    title: 'Count of Smaller Numbers After Self',
    slug: 'count-of-smaller-numbers-after-self',
    leetcodeUrl: leetCodeUrl('count-of-smaller-numbers-after-self'),
    difficulty: 'Hard',
    dataStructures: ['fenwick-tree', 'segment-tree'],
    patterns: ['coordinate-compression-bit'],
  },
  {
    id: 'number-of-provinces',
    title: 'Number of Provinces',
    slug: 'number-of-provinces',
    leetcodeUrl: leetCodeUrl('number-of-provinces'),
    difficulty: 'Medium',
    dataStructures: ['union-find'],
    patterns: ['union-all-edges'],
  },
  {
    id: 'redundant-connection',
    title: 'Redundant Connection',
    slug: 'redundant-connection',
    leetcodeUrl: leetCodeUrl('redundant-connection'),
    difficulty: 'Medium',
    dataStructures: ['union-find'],
    patterns: ['first-cycle-edge'],
  },
  {
    id: 'number-of-islands',
    title: 'Number of Islands',
    slug: 'number-of-islands',
    leetcodeUrl: leetCodeUrl('number-of-islands'),
    difficulty: 'Medium',
    dataStructures: ['graph-representations'],
    patterns: ['grid-dfs-flood'],
  },
  {
    id: 'max-area-of-island',
    title: 'Max Area of Island',
    slug: 'max-area-of-island',
    leetcodeUrl: leetCodeUrl('max-area-of-island'),
    difficulty: 'Medium',
    dataStructures: ['graph-representations'],
    patterns: ['grid-dfs-area'],
  },
  {
    id: 'network-delay-time',
    title: 'Network Delay Time',
    slug: 'network-delay-time',
    leetcodeUrl: leetCodeUrl('network-delay-time'),
    difficulty: 'Medium',
    dataStructures: ['weighted-graph', 'heap'],
    patterns: ['dijkstra-source'],
  },
  {
    id: 'cheapest-flights-within-k-stops',
    title: 'Cheapest Flights Within K Stops',
    slug: 'cheapest-flights-within-k-stops',
    leetcodeUrl: leetCodeUrl('cheapest-flights-within-k-stops'),
    difficulty: 'Medium',
    dataStructures: ['weighted-graph'],
    patterns: ['bounded-bellman-ford'],
  },
  {
    id: 'course-schedule',
    title: 'Course Schedule',
    slug: 'course-schedule',
    leetcodeUrl: leetCodeUrl('course-schedule'),
    difficulty: 'Medium',
    dataStructures: ['advanced-graphs'],
    patterns: ['cycle-detect-directed'],
  },
  {
    id: 'course-schedule-ii',
    title: 'Course Schedule II',
    slug: 'course-schedule-ii',
    leetcodeUrl: leetCodeUrl('course-schedule-ii'),
    difficulty: 'Medium',
    dataStructures: ['advanced-graphs'],
    patterns: ['kahns-topo-order'],
  },
  {
    id: 'is-graph-bipartite',
    title: 'Is Graph Bipartite?',
    slug: 'is-graph-bipartite',
    leetcodeUrl: leetCodeUrl('is-graph-bipartite'),
    difficulty: 'Medium',
    dataStructures: ['advanced-graphs'],
    patterns: ['two-color-bfs'],
  },
  {
    id: 'missing-number',
    title: 'Missing Number',
    slug: 'missing-number',
    leetcodeUrl: leetCodeUrl('missing-number'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['linear-scan'],
  },
  {
    id: 'binary-search',
    title: 'Binary Search',
    slug: 'binary-search',
    leetcodeUrl: leetCodeUrl('binary-search'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['halving-range'],
  },
  {
    id: 'search-insert-position',
    title: 'Search Insert Position',
    slug: 'search-insert-position',
    leetcodeUrl: leetCodeUrl('search-insert-position'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['lower-bound'],
  },
  {
    id: 'first-bad-version',
    title: 'First Bad Version',
    slug: 'first-bad-version',
    leetcodeUrl: leetCodeUrl('first-bad-version'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['lower-bound'],
  },
  {
    id: 'sort-colors',
    title: 'Sort Colors',
    slug: 'sort-colors',
    leetcodeUrl: leetCodeUrl('sort-colors'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['dutch-flag'],
  },
  {
    id: 'height-checker',
    title: 'Height Checker',
    slug: 'height-checker',
    leetcodeUrl: leetCodeUrl('height-checker'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['counting-compare'],
  },
  {
    id: 'sort-an-array',
    title: 'Sort an Array',
    slug: 'sort-an-array',
    leetcodeUrl: leetCodeUrl('sort-an-array'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['general-sorting'],
  },
  {
    id: 'squares-of-a-sorted-array',
    title: 'Squares of a Sorted Array',
    slug: 'squares-of-a-sorted-array',
    leetcodeUrl: leetCodeUrl('squares-of-a-sorted-array'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['two-pointers-ends'],
  },
  {
    id: 'merge-intervals',
    title: 'Merge Intervals',
    slug: 'merge-intervals',
    leetcodeUrl: leetCodeUrl('merge-intervals'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['sort-then-sweep'],
  },
  {
    id: 'h-index',
    title: 'H-Index',
    slug: 'h-index',
    leetcodeUrl: leetCodeUrl('h-index'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['counting-sort'],
  },
  {
    id: 'two-sum-ii-input-array-is-sorted',
    title: 'Two Sum II - Input Array Is Sorted',
    slug: 'two-sum-ii-input-array-is-sorted',
    leetcodeUrl: leetCodeUrl('two-sum-ii-input-array-is-sorted'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['converging-pointers'],
  },
  {
    id: 'container-with-most-water',
    title: 'Container With Most Water',
    slug: 'container-with-most-water',
    leetcodeUrl: leetCodeUrl('container-with-most-water'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['converging-pointers'],
  },
  {
    id: '3sum',
    title: '3Sum',
    slug: '3sum',
    leetcodeUrl: leetCodeUrl('3sum'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['sort-plus-converging'],
  },
  {
    id: 'remove-duplicates-from-sorted-array',
    title: 'Remove Duplicates from Sorted Array',
    slug: 'remove-duplicates-from-sorted-array',
    leetcodeUrl: leetCodeUrl('remove-duplicates-from-sorted-array'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['slow-fast-write'],
  },
  {
    id: 'minimum-window-substring',
    title: 'Minimum Window Substring',
    slug: 'minimum-window-substring',
    leetcodeUrl: leetCodeUrl('minimum-window-substring'),
    difficulty: 'Hard',
    dataStructures: ['string', 'hash-table'],
    patterns: ['flexible-window'],
  },
  {
    id: 'longest-repeating-character-replacement',
    title: 'Longest Repeating Character Replacement',
    slug: 'longest-repeating-character-replacement',
    leetcodeUrl: leetCodeUrl('longest-repeating-character-replacement'),
    difficulty: 'Medium',
    dataStructures: ['string'],
    patterns: ['flexible-window'],
  },
  {
    id: 'permutation-in-string',
    title: 'Permutation in String',
    slug: 'permutation-in-string',
    leetcodeUrl: leetCodeUrl('permutation-in-string'),
    difficulty: 'Medium',
    dataStructures: ['string', 'hash-table'],
    patterns: ['fixed-window-counts'],
  },
  {
    id: 'subarray-sum-equals-k',
    title: 'Subarray Sum Equals K',
    slug: 'subarray-sum-equals-k',
    leetcodeUrl: leetCodeUrl('subarray-sum-equals-k'),
    difficulty: 'Medium',
    dataStructures: ['array', 'hash-table'],
    patterns: ['prefix-map'],
  },
  {
    id: 'find-pivot-index',
    title: 'Find Pivot Index',
    slug: 'find-pivot-index',
    leetcodeUrl: leetCodeUrl('find-pivot-index'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['prefix-sums'],
  },
  {
    id: 'product-of-array-except-self',
    title: 'Product of Array Except Self',
    slug: 'product-of-array-except-self',
    leetcodeUrl: leetCodeUrl('product-of-array-except-self'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['prefix-suffix-passes'],
  },
  {
    id: 'middle-of-the-linked-list',
    title: 'Middle of the Linked List',
    slug: 'middle-of-the-linked-list',
    leetcodeUrl: leetCodeUrl('middle-of-the-linked-list'),
    difficulty: 'Easy',
    dataStructures: ['singly-linked-list'],
    patterns: ['tortoise-and-hare'],
  },
  {
    id: 'find-the-duplicate-number',
    title: 'Find the Duplicate Number',
    slug: 'find-the-duplicate-number',
    leetcodeUrl: leetCodeUrl('find-the-duplicate-number'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['cycle-detect-values'],
  },
  {
    id: 'subsets',
    title: 'Subsets',
    slug: 'subsets',
    leetcodeUrl: leetCodeUrl('subsets'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['include-exclude'],
  },
  {
    id: 'permutations',
    title: 'Permutations',
    slug: 'permutations',
    leetcodeUrl: leetCodeUrl('permutations'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['used-set-dfs'],
  },
  {
    id: 'combination-sum',
    title: 'Combination Sum',
    slug: 'combination-sum',
    leetcodeUrl: leetCodeUrl('combination-sum'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['reuse-branch-dfs'],
  },
  {
    id: 'fibonacci-number',
    title: 'Fibonacci Number',
    slug: 'fibonacci-number',
    leetcodeUrl: leetCodeUrl('fibonacci-number'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['recurrence-memo'],
  },
  {
    id: 'climbing-stairs',
    title: 'Climbing Stairs',
    slug: 'climbing-stairs',
    leetcodeUrl: leetCodeUrl('climbing-stairs'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['fib-like-dp'],
  },
  {
    id: 'powx-n',
    title: 'Pow(x, n)',
    slug: 'powx-n',
    leetcodeUrl: leetCodeUrl('powx-n'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['halving-recursion'],
  },
  {
    id: 'maximum-subarray',
    title: 'Maximum Subarray',
    slug: 'maximum-subarray',
    leetcodeUrl: leetCodeUrl('maximum-subarray'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['divide-crossing'],
  },
  {
    id: 'search-a-2d-matrix',
    title: 'Search a 2D Matrix',
    slug: 'search-a-2d-matrix',
    leetcodeUrl: leetCodeUrl('search-a-2d-matrix'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['flattened-binary-search'],
  },
  {
    id: 'jump-game',
    title: 'Jump Game',
    slug: 'jump-game',
    leetcodeUrl: leetCodeUrl('jump-game'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['reach-tracking'],
  },
  {
    id: 'jump-game-ii',
    title: 'Jump Game II',
    slug: 'jump-game-ii',
    leetcodeUrl: leetCodeUrl('jump-game-ii'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['jump-on-exhaustion'],
  },
  {
    id: 'gas-station',
    title: 'Gas Station',
    slug: 'gas-station',
    leetcodeUrl: leetCodeUrl('gas-station'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['restart-on-deficit'],
  },
  {
    id: 'assign-cookies',
    title: 'Assign Cookies',
    slug: 'assign-cookies',
    leetcodeUrl: leetCodeUrl('assign-cookies'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['sort-then-greedy'],
  },
  {
    id: 'binary-tree-level-order-traversal',
    title: 'Binary Tree Level Order Traversal',
    slug: 'binary-tree-level-order-traversal',
    leetcodeUrl: leetCodeUrl('binary-tree-level-order-traversal'),
    difficulty: 'Medium',
    dataStructures: ['binary-tree', 'queue-deque'],
    patterns: ['wave-snapshot'],
  },
  {
    id: 'rotting-oranges',
    title: 'Rotting Oranges',
    slug: 'rotting-oranges',
    leetcodeUrl: leetCodeUrl('rotting-oranges'),
    difficulty: 'Medium',
    dataStructures: ['queue-deque'],
    patterns: ['multi-source-bfs'],
  },
  {
    id: 'word-ladder',
    title: 'Word Ladder',
    slug: 'word-ladder',
    leetcodeUrl: leetCodeUrl('word-ladder'),
    difficulty: 'Hard',
    dataStructures: ['queue-deque', 'hash-set'],
    patterns: ['implicit-graph-bfs'],
  },
  {
    id: 'clone-graph',
    title: 'Clone Graph',
    slug: 'clone-graph',
    leetcodeUrl: leetCodeUrl('clone-graph'),
    difficulty: 'Medium',
    dataStructures: ['hash-table'],
    patterns: ['dfs-copy-map'],
  },
  {
    id: 'pacific-atlantic-water-flow',
    title: 'Pacific Atlantic Water Flow',
    slug: 'pacific-atlantic-water-flow',
    leetcodeUrl: leetCodeUrl('pacific-atlantic-water-flow'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['reverse-shore-dfs'],
  },
  {
    id: 'find-eventual-safe-states',
    title: 'Find Eventual Safe States',
    slug: 'find-eventual-safe-states',
    leetcodeUrl: leetCodeUrl('find-eventual-safe-states'),
    difficulty: 'Medium',
    dataStructures: ['advanced-graphs'],
    patterns: ['reverse-topo-trim'],
  },
  {
    id: 'path-with-minimum-effort',
    title: 'Path With Minimum Effort',
    slug: 'path-with-minimum-effort',
    leetcodeUrl: leetCodeUrl('path-with-minimum-effort'),
    difficulty: 'Medium',
    dataStructures: ['weighted-graph', 'heap'],
    patterns: ['bottleneck-dijkstra'],
  },
  {
    id: 'graph-valid-tree',
    title: 'Graph Valid Tree',
    slug: 'graph-valid-tree',
    leetcodeUrl: leetCodeUrl('graph-valid-tree'),
    difficulty: 'Medium',
    dataStructures: ['union-find'],
    patterns: ['edges-equals-vertices-minus-one'],
  },
  {
    id: 'min-cost-to-connect-all-points',
    title: 'Min Cost to Connect All Points',
    slug: 'min-cost-to-connect-all-points',
    leetcodeUrl: leetCodeUrl('min-cost-to-connect-all-points'),
    difficulty: 'Medium',
    dataStructures: ['weighted-graph', 'union-find'],
    patterns: ['complete-graph-mst'],
  },
  {
    id: 'house-robber',
    title: 'House Robber',
    slug: 'house-robber',
    leetcodeUrl: leetCodeUrl('house-robber'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['skip-or-take-dp'],
  },
  {
    id: 'coin-change',
    title: 'Coin Change',
    slug: 'coin-change',
    leetcodeUrl: leetCodeUrl('coin-change'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['min-over-coins'],
  },
  {
    id: 'unique-paths',
    title: 'Unique Paths',
    slug: 'unique-paths',
    leetcodeUrl: leetCodeUrl('unique-paths'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['grid-combine'],
  },
  {
    id: 'longest-common-subsequence',
    title: 'Longest Common Subsequence',
    slug: 'longest-common-subsequence',
    leetcodeUrl: leetCodeUrl('longest-common-subsequence'),
    difficulty: 'Medium',
    dataStructures: ['string'],
    patterns: ['diagonal-match-dp'],
  },
  {
    id: 'edit-distance',
    title: 'Edit Distance',
    slug: 'edit-distance',
    leetcodeUrl: leetCodeUrl('edit-distance'),
    difficulty: 'Hard',
    dataStructures: ['string'],
    patterns: ['three-neighbor-dp'],
  },
  {
    id: 'minimum-path-sum',
    title: 'Minimum Path Sum',
    slug: 'minimum-path-sum',
    leetcodeUrl: leetCodeUrl('minimum-path-sum'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['grid-min-dp'],
  },
  {
    id: 'partition-equal-subset-sum',
    title: 'Partition Equal Subset Sum',
    slug: 'partition-equal-subset-sum',
    leetcodeUrl: leetCodeUrl('partition-equal-subset-sum'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['half-sum-subset'],
  },
  {
    id: 'coin-change-ii',
    title: 'Coin Change II',
    slug: 'coin-change-ii',
    leetcodeUrl: leetCodeUrl('coin-change-ii'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['unbounded-count-dp'],
  },
  {
    id: 'target-sum',
    title: 'Target Sum',
    slug: 'target-sum',
    leetcodeUrl: leetCodeUrl('target-sum'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['subset-transform'],
  },
  {
    id: 'ones-and-zeroes',
    title: 'Ones and Zeroes',
    slug: 'ones-and-zeroes',
    leetcodeUrl: leetCodeUrl('ones-and-zeroes'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['two-capacity-knapsack'],
  },
  {
    id: 'design-hashmap',
    title: 'Design HashMap',
    slug: 'design-hashmap',
    leetcodeUrl: leetCodeUrl('design-hashmap'),
    difficulty: 'Easy',
    dataStructures: ['hash-table'],
    patterns: ['separate-chaining'],
  },
  {
    id: 'single-number',
    title: 'Single Number',
    slug: 'single-number',
    leetcodeUrl: leetCodeUrl('single-number'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['xor-cancel'],
  },
  {
    id: 'number-of-1-bits',
    title: 'Number of 1 Bits',
    slug: 'number-of-1-bits',
    leetcodeUrl: leetCodeUrl('number-of-1-bits'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['lowbit-peel'],
  },
  {
    id: 'counting-bits',
    title: 'Counting Bits',
    slug: 'counting-bits',
    leetcodeUrl: leetCodeUrl('counting-bits'),
    difficulty: 'Easy',
    dataStructures: ['array'],
    patterns: ['dp-lowbit'],
  },
  {
    id: 'daily-temperatures',
    title: 'Daily Temperatures',
    slug: 'daily-temperatures',
    leetcodeUrl: leetCodeUrl('daily-temperatures'),
    difficulty: 'Medium',
    dataStructures: ['stack'],
    patterns: ['monotonic-stack'],
  },
  {
    id: 'next-greater-element-i',
    title: 'Next Greater Element I',
    slug: 'next-greater-element-i',
    leetcodeUrl: leetCodeUrl('next-greater-element-i'),
    difficulty: 'Easy',
    dataStructures: ['stack', 'hash-table'],
    patterns: ['monotonic-stack'],
  },
  {
    id: 'largest-rectangle-in-histogram',
    title: 'Largest Rectangle in Histogram',
    slug: 'largest-rectangle-in-histogram',
    leetcodeUrl: leetCodeUrl('largest-rectangle-in-histogram'),
    difficulty: 'Hard',
    dataStructures: ['stack'],
    patterns: ['monotonic-boundaries'],
  },
  {
    id: 'trapping-rain-water',
    title: 'Trapping Rain Water',
    slug: 'trapping-rain-water',
    leetcodeUrl: leetCodeUrl('trapping-rain-water'),
    difficulty: 'Hard',
    dataStructures: ['stack', 'array'],
    patterns: ['monotonic-valleys'],
  },
  {
    id: 'insert-interval',
    title: 'Insert Interval',
    slug: 'insert-interval',
    leetcodeUrl: leetCodeUrl('insert-interval'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['splice-sweep'],
  },
  {
    id: 'non-overlapping-intervals',
    title: 'Non-overlapping Intervals',
    slug: 'non-overlapping-intervals',
    leetcodeUrl: leetCodeUrl('non-overlapping-intervals'),
    difficulty: 'Medium',
    dataStructures: ['array'],
    patterns: ['earliest-finish-greedy'],
  },
  {
    id: 'copy-list-with-random-pointer',
    title: 'Copy List with Random Pointer',
    slug: 'copy-list-with-random-pointer',
    leetcodeUrl: leetCodeUrl('copy-list-with-random-pointer'),
    difficulty: 'Medium',
    dataStructures: ['singly-linked-list', 'hash-table'],
    patterns: ['interleave-clone'],
  },
  {
    id: 'reverse-string',
    title: 'Reverse String',
    slug: 'reverse-string',
    leetcodeUrl: leetCodeUrl('reverse-string'),
    difficulty: 'Easy',
    dataStructures: ['string'],
    patterns: ['inward-swap'],
  },
  {
    id: 'implement-stack-using-queues',
    title: 'Implement Stack using Queues',
    slug: 'implement-stack-using-queues',
    leetcodeUrl: leetCodeUrl('implement-stack-using-queues'),
    difficulty: 'Easy',
    dataStructures: ['queue-deque', 'stack'],
    patterns: ['rotate-on-push'],
  },
];
