import type { Sheet } from '../../types/content.ts';

/**
 * S4J SDE: ninety days across every topic on this site — data structures,
 * algorithms, graphs, dynamic programming, and the collections framework —
 * with a revision day every seventh day, hardening weeks, mocks, and a
 * graduation capstone.
 */
export const s4j90DaysSde: Sheet = {
  slug: 's4j-90-days-sde',
  title: 'S4J 90-Day SDE',
  description:
    'Ninety days to SDE-ready: every topic on this site — data structures, algorithms, graphs, dynamic programming, and Java collections — with weekly revision, hardening weeks, mocks, and a graduation capstone.',
  difficulty: 'Advanced',
  days: [
    {
      day: 1,
      title: 'Complexity glasses on',
      topicSlugs: ['big-o-notation', 'problem-solving-framework'],
      problemIds: ['two-sum', 'contains-duplicate'],
      goal: 'Rank loops by growth and run the full solve loop twice.',
    },
    {
      day: 2,
      title: 'Array mechanics',
      topicSlugs: ['array', 'dynamic-array'],
      problemIds: ['best-time-to-buy-and-sell-stock', 'move-zeroes'],
      goal: 'Shift and grow arrays by hand before trusting ArrayList.',
    },
    {
      day: 3,
      title: 'Search ladder',
      topicSlugs: ['linear-search', 'binary-search'],
      problemIds: ['binary-search', 'first-bad-version'],
      goal: 'Lower-bound thinking, not just lookup.',
    },
    {
      day: 4,
      title: 'String craft',
      topicSlugs: ['string', 'pass-by-value-java'],
      problemIds: ['valid-anagram', 'reverse-string'],
      goal: 'Two-pointer strings; predict every mutation.',
    },
    {
      day: 5,
      title: 'Nodes and references',
      topicSlugs: ['memory-stack-vs-heap', 'singly-linked-list'],
      problemIds: ['reverse-linked-list', 'middle-of-the-linked-list'],
      goal: 'Draw the heap for a reversal; dummy heads everywhere.',
    },
    {
      day: 6,
      title: 'LIFO vs FIFO',
      topicSlugs: ['stack', 'queue-deque'],
      problemIds: ['valid-parentheses', 'number-of-recent-calls'],
      goal: 'Match discipline to problem; queues from stacks.',
    },
    {
      day: 7,
      title: 'Revision: week 1',
      topicSlugs: ['array', 'binary-search'],
      problemIds: ['two-sum', 'search-insert-position'],
      goal: 'Re-solve week one blind; log every hesitation.',
    },
    {
      day: 8,
      title: 'Amortized cost and hashing',
      topicSlugs: ['amortized-analysis', 'hashmap-internals'],
      problemIds: ['group-anagrams', 'design-hashmap'],
      goal: 'Argue doubling, ship a chained map, explain bucket mechanics.',
    },
    {
      day: 9,
      title: 'Equality and sets',
      topicSlugs: ['equals-hashcode-contract', 'hashset-jcf'],
      problemIds: ['happy-number', 'intersection-of-two-arrays'],
      goal: 'Correct value types plus cycle-by-set detection.',
    },
    {
      day: 10,
      title: 'Ranges and pairs',
      topicSlugs: ['prefix-sum', 'two-pointers'],
      problemIds: ['find-pivot-index', '3sum'],
      goal: 'O(1) range sums and a sorted triple scan.',
    },
    {
      day: 11,
      title: 'Window discipline',
      topicSlugs: ['sliding-window'],
      problemIds: ['longest-substring-without-repeating-characters', 'best-time-to-buy-and-sell-stock'],
      goal: 'State the validity invariant before coding.',
    },
    {
      day: 12,
      title: 'Quadratic sorts',
      topicSlugs: ['bubble-sort', 'selection-sort'],
      problemIds: ['sort-colors', 'height-checker'],
      goal: 'Trace both by hand; name stability outcomes.',
    },
    {
      day: 13,
      title: 'Adaptive and counting sorts',
      topicSlugs: ['insertion-sort', 'counting-sort'],
      problemIds: ['h-index', 'majority-element'],
      goal: 'Shift-based insertion and range-limited counting.',
    },
    {
      day: 14,
      title: 'Revision: weeks 1-2',
      topicSlugs: ['hash-table', 'sliding-window'],
      problemIds: ['top-k-frequent-elements', 'permutation-in-string'],
      goal: 'Mixed re-solve: key design plus window counters.',
    },
    {
      day: 15,
      title: 'Merge and quick',
      topicSlugs: ['merge-sort', 'quick-sort'],
      problemIds: ['merge-intervals', 'kth-largest-element-in-an-array'],
      goal: 'Stable merges vs pivot defense, complexity narrated.',
    },
    {
      day: 16,
      title: 'Tree walks',
      topicSlugs: ['binary-tree', 'recursion-call-stack'],
      problemIds: ['maximum-depth-of-binary-tree', 'diameter-of-binary-tree'],
      goal: 'Height-returning recursion with depth awareness.',
    },
    {
      day: 17,
      title: 'Ordered trees',
      topicSlugs: ['binary-search-tree', 'comparable-vs-comparator'],
      problemIds: ['validate-binary-search-tree', 'kth-smallest-element-in-a-bst'],
      goal: 'Bounds validation and custom orderings.',
    },
    {
      day: 18,
      title: 'Priority in practice',
      topicSlugs: ['heap', 'priorityqueue-jcf'],
      problemIds: ['last-stone-weight', 'k-closest-points-to-origin'],
      goal: 'Heap simulations plus PriorityQueue comparator craft.',
    },
    {
      day: 19,
      title: 'Prefixes and recurrence',
      topicSlugs: ['trie', 'recursion-tree'],
      problemIds: ['implement-trie-prefix-tree', 'powx-n'],
      goal: 'Shared prefixes and halving recurrences.',
    },
    {
      day: 20,
      title: 'Cycles and cursors',
      topicSlugs: ['fast-slow-pointers', 'doubly-linked-list'],
      problemIds: ['linked-list-cycle', 'add-two-numbers'],
      goal: 'Tortoise-and-hare plus carry walks.',
    },
    {
      day: 21,
      title: 'Revision: sorts and trees',
      topicSlugs: ['quick-sort', 'binary-tree'],
      problemIds: ['sort-an-array', 'invert-binary-tree'],
      goal: 'Re-derive partition logic; mirror a tree blind.',
    },
    {
      day: 22,
      title: 'Split and enumerate',
      topicSlugs: ['divide-and-conquer', 'backtracking'],
      problemIds: ['maximum-subarray', 'subsets'],
      goal: 'Crossing combines and include/exclude with undo.',
    },
    {
      day: 23,
      title: 'Greed and bits',
      topicSlugs: ['greedy', 'bit-manipulation'],
      problemIds: ['jump-game', 'single-number'],
      goal: 'Exchange arguments and XOR cancellation.',
    },
    {
      day: 24,
      title: 'Sweeps and monotonicity',
      topicSlugs: ['interval-problems', 'monotonic-stack-queue'],
      problemIds: ['non-overlapping-intervals', 'daily-temperatures'],
      goal: 'Earliest-finish greed and next-greater scans.',
    },
    {
      day: 25,
      title: 'Range trees',
      topicSlugs: ['segment-tree', 'fenwick-tree'],
      problemIds: ['range-sum-query-mutable', 'range-sum-query-immutable'],
      goal: 'Updates decide the structure: segtree vs BIT vs prefix.',
    },
    {
      day: 26,
      title: 'Union and adjacency',
      topicSlugs: ['union-find', 'graph-representations'],
      problemIds: ['number-of-provinces', 'number-of-islands'],
      goal: 'Union-all-edges provinces and grid floods.',
    },
    {
      day: 27,
      title: 'BFS and DFS',
      topicSlugs: ['bfs', 'dfs'],
      problemIds: ['binary-tree-level-order-traversal', 'max-area-of-island'],
      goal: 'Waves vs dives on the same graph, orders compared.',
    },
    {
      day: 28,
      title: 'Revision: techniques',
      topicSlugs: ['backtracking', 'greedy'],
      problemIds: ['permutations', 'gas-station'],
      goal: 'Used-set DFS and restart-on-deficit, timed.',
    },
    {
      day: 29,
      title: 'Weighted routes',
      topicSlugs: ['weighted-graph', 'dijkstra'],
      problemIds: ['network-delay-time', 'path-with-minimum-effort'],
      goal: 'Heap Dijkstra with stale skips; bottleneck variants.',
    },
    {
      day: 30,
      title: 'Negatives and order',
      topicSlugs: ['bellman-ford', 'topological-sort'],
      problemIds: ['cheapest-flights-within-k-stops', 'course-schedule-ii'],
      goal: 'Round-limited relaxations and Kahn with verdict.',
    },
    {
      day: 31,
      title: 'Cycles and spanning trees',
      topicSlugs: ['union-find-cycle-detection', 'kruskal'],
      problemIds: ['redundant-connection', 'min-cost-to-connect-all-points'],
      goal: 'First-cycle edge plus sort-and-union MST.',
    },
    {
      day: 32,
      title: 'Growing trees and advanced graphs',
      topicSlugs: ['prim', 'advanced-graphs'],
      problemIds: ['is-graph-bipartite', 'find-eventual-safe-states'],
      goal: 'Frontier-grown MSTs and two-color safety analysis.',
    },
    {
      day: 33,
      title: '1D DP foundations',
      topicSlugs: ['dynamic-programming-1d'],
      problemIds: ['climbing-stairs', 'house-robber'],
      goal: 'States, transitions, and rolling compression.',
    },
    {
      day: 34,
      title: '2D DP foundations',
      topicSlugs: ['dynamic-programming-2d'],
      problemIds: ['unique-paths', 'longest-common-subsequence'],
      goal: 'Grid fills and diagonal-match tables.',
    },
    {
      day: 35,
      title: 'Revision: graphs and DP starts',
      topicSlugs: ['dijkstra', 'dynamic-programming-1d'],
      problemIds: ['network-delay-time', 'coin-change'],
      goal: 'Settled-set discipline plus min-over-coins.',
    },
    {
      day: 36,
      title: 'Knapsack day',
      topicSlugs: ['knapsack'],
      problemIds: ['partition-equal-subset-sum', 'target-sum'],
      goal: 'Take-or-skip tables and subset transforms.',
    },
    {
      day: 37,
      title: 'Heaps under pressure',
      topicSlugs: ['heap-sort', 'heap'],
      problemIds: ['task-scheduler', 'find-median-from-data-stream'],
      goal: 'Cooldown counting and two-heap balance.',
    },
    {
      day: 38,
      title: 'Trees under pressure',
      topicSlugs: ['binary-tree', 'binary-search-tree'],
      problemIds: ['binary-tree-maximum-path-sum', 'construct-binary-tree-from-preorder-and-inorder-traversal'],
      goal: 'Gain-or-drop paths and root-split builds.',
    },
    {
      day: 39,
      title: 'Backtracking under pressure',
      topicSlugs: ['backtracking', 'trie'],
      problemIds: ['word-search-ii', 'n-queens'],
      goal: 'Trie-pruned boards and constraint sets.',
    },
    {
      day: 40,
      title: 'Windows under pressure',
      topicSlugs: ['sliding-window', 'prefix-sum'],
      problemIds: ['minimum-window-substring', 'subarray-sum-equals-k'],
      goal: 'Two hard windows with validity proofs.',
    },
    {
      day: 41,
      title: 'Graphs under pressure',
      topicSlugs: ['bfs', 'dfs'],
      problemIds: ['word-ladder', 'clone-graph'],
      goal: 'Implicit graphs and copy-maps at speed.',
    },
    {
      day: 42,
      title: 'Revision: half-way audit',
      topicSlugs: ['problem-solving-framework', 'big-o-notation'],
      problemIds: ['two-sum', 'valid-parentheses'],
      goal: 'Re-run day one; list every remaining weak pattern.',
    },
    {
      day: 43,
      title: 'DP under pressure',
      topicSlugs: ['dynamic-programming-2d', 'knapsack'],
      problemIds: ['edit-distance', 'coin-change-ii'],
      goal: 'Three-neighbor tables and unbounded counting.',
    },
    {
      day: 44,
      title: 'Strings deep cut',
      topicSlugs: ['string', 'dynamic-programming-1d'],
      problemIds: ['longest-palindromic-substring', 'decode-ways'],
      goal: 'Center expansion and one-two-step decoding.',
    },
    {
      day: 45,
      title: 'Linked lists deep cut',
      topicSlugs: ['singly-linked-list', 'fast-slow-pointers'],
      problemIds: ['reorder-list', 'copy-list-with-random-pointer'],
      goal: 'Split-reverse-merge and interleave cloning.',
    },
    {
      day: 46,
      title: 'Stack and queue deep cut',
      topicSlugs: ['arraydeque-jcf', 'stack'],
      problemIds: ['evaluate-reverse-polish-notation', 'largest-rectangle-in-histogram'],
      goal: 'Postfix machines and boundary stacks on ArrayDeque.',
    },
    {
      day: 47,
      title: 'Binary search deep cut',
      topicSlugs: ['binary-search', 'heap'],
      problemIds: ['median-of-two-sorted-arrays', 'kth-largest-element-in-an-array'],
      goal: 'Partition halves and size-k heaps, both timed.',
    },
    {
      day: 48,
      title: 'Math and geometry',
      topicSlugs: ['binary-search', 'graph-representations'],
      problemIds: ['rotate-image', 'spiral-matrix'],
      goal: 'In-place transforms with layer discipline.',
    },
    {
      day: 49,
      title: 'Revision: structures sprint',
      topicSlugs: ['stack', 'heap'],
      problemIds: ['min-stack', 'kth-largest-element-in-an-array'],
      goal: 'Auxiliary-state designs at interview pace.',
    },
    {
      day: 50,
      title: 'Bit tricks sprint',
      topicSlugs: ['bit-manipulation'],
      problemIds: ['number-of-1-bits', 'reverse-bits'],
      goal: 'Lowbit peeling and mirror loops from memory.',
    },
    {
      day: 51,
      title: 'Intervals sprint',
      topicSlugs: ['interval-problems', 'greedy'],
      problemIds: ['merge-intervals', 'jump-game-ii'],
      goal: 'Sweep merges and jump-on-exhaustion.',
    },
    {
      day: 52,
      title: 'Monotonic sprint',
      topicSlugs: ['monotonic-structures', 'stack'],
      problemIds: ['daily-temperatures', 'trapping-rain-water'],
      goal: 'Next-greater scans and valley filling.',
    },
    {
      day: 53,
      title: 'Union-find sprint',
      topicSlugs: ['union-find', 'union-find-cycle-detection'],
      problemIds: ['number-of-connected-components-in-an-undirected-graph', 'graph-valid-tree'],
      goal: 'Union-all-edges plus the V−1 edge rule.',
    },
    {
      day: 54,
      title: 'Segment sprint',
      topicSlugs: ['segment-tree', 'fenwick-tree'],
      problemIds: ['range-sum-query-mutable', 'count-of-smaller-numbers-after-self'],
      goal: 'Range structures with updates, timed.',
    },
    {
      day: 55,
      title: 'Trie sprint',
      topicSlugs: ['trie', 'string'],
      problemIds: ['design-add-and-search-words-data-structure', 'word-search'],
      goal: 'Wildcard DFS and board backtracking.',
    },
    {
      day: 56,
      title: 'Revision: sprint review',
      topicSlugs: ['interval-problems', 'bit-manipulation'],
      problemIds: ['insert-interval', 'single-number'],
      goal: 'Splice sweeps and XOR cancellation, no notes.',
    },
    {
      day: 57,
      title: 'Mock: arrays and hashing',
      topicSlugs: ['array', 'hash-table'],
      problemIds: ['two-sum', 'group-anagrams', 'best-time-to-buy-and-sell-stock'],
      goal: '45-minute timed trio, tested edge cases.',
    },
    {
      day: 58,
      title: 'Mock: trees',
      topicSlugs: ['binary-tree', 'binary-search-tree'],
      problemIds: ['invert-binary-tree', 'validate-binary-search-tree'],
      goal: '45-minute pair with drawn call trees.',
    },
    {
      day: 59,
      title: 'Mock: graphs',
      topicSlugs: ['bfs', 'union-find'],
      problemIds: ['number-of-islands', 'redundant-connection', 'rotting-oranges'],
      goal: '60-minute trio: flood, cycle, multi-source.',
    },
    {
      day: 60,
      title: 'Mock: DP',
      topicSlugs: ['dynamic-programming-1d', 'knapsack'],
      problemIds: ['house-robber', 'coin-change', 'target-sum'],
      goal: '60-minute trio: states and transitions aloud.',
    },
    {
      day: 61,
      title: 'Mock: techniques',
      topicSlugs: ['two-pointers', 'backtracking'],
      problemIds: ['container-with-most-water', 'subsets'],
      goal: 'Converging scan plus include/exclude, timed.',
    },
    {
      day: 62,
      title: 'Mock: heaps and sorts',
      topicSlugs: ['heap', 'quick-sort'],
      problemIds: ['top-k-frequent-elements', 'sort-an-array'],
      goal: 'Frequency heaps and defended pivots.',
    },
    {
      day: 63,
      title: 'Revision: mock debrief',
      topicSlugs: ['problem-solving-framework'],
      problemIds: ['valid-palindrome', 'contains-duplicate'],
      goal: 'Convert every mock stumble into a drill card.',
    },
    {
      day: 64,
      title: 'Hard day: trees',
      topicSlugs: ['binary-tree', 'trie'],
      problemIds: ['serialize-and-deserialize-binary-tree', 'word-search-ii'],
      goal: 'Preorder codecs and pruned searches.',
    },
    {
      day: 65,
      title: 'Hard day: windows and stacks',
      topicSlugs: ['sliding-window', 'stack'],
      problemIds: ['sliding-window-maximum', 'largest-rectangle-in-histogram'],
      goal: 'Monotonic structures at their hardest.',
    },
    {
      day: 66,
      title: 'Hard day: graphs and DP',
      topicSlugs: ['advanced-graphs', 'dynamic-programming-2d'],
      problemIds: ['alien-dictionary', 'burst-balloons'],
      goal: 'Topo character order and last-burst intervals.',
    },
    {
      day: 67,
      title: 'System-flavored mediums',
      topicSlugs: ['linkedhashmap-lru', 'hashmap-internals'],
      problemIds: ['lru-cache', 'design-twitter'],
      goal: 'LRU eviction plus feed design narration.',
    },
    {
      day: 68,
      title: 'Speed round: easies',
      topicSlugs: ['array', 'string'],
      problemIds: ['two-sum', 'valid-palindrome', 'best-time-to-buy-and-sell-stock'],
      goal: 'Three easies in 30 minutes, zero stumbles.',
    },
    {
      day: 69,
      title: 'Speed round: mediums',
      topicSlugs: ['hash-table', 'two-pointers'],
      problemIds: ['group-anagrams', '3sum'],
      goal: 'Two mediums in 45 with tested edges.',
    },
    {
      day: 70,
      title: 'Revision: hard postmortems',
      topicSlugs: ['binary-tree', 'sliding-window'],
      problemIds: ['diameter-of-binary-tree', 'longest-substring-without-repeating-characters'],
      goal: 'Re-solve failed hards at one level down.',
    },
    {
      day: 71,
      title: 'Weak-spot surgery I',
      topicSlugs: ['dynamic-programming-1d', 'backtracking'],
      problemIds: ['coin-change', 'combination-sum'],
      goal: 'Unbounded vs reuse-branch decisions, drilled.',
    },
    {
      day: 72,
      title: 'Weak-spot surgery II',
      topicSlugs: ['graph-representations', 'dijkstra'],
      problemIds: ['clone-graph', 'network-delay-time'],
      goal: 'Copy-maps and stale-entry skips, drilled.',
    },
    {
      day: 73,
      title: 'Full mock I',
      topicSlugs: ['array', 'binary-tree'],
      problemIds: ['product-of-array-except-self', 'balanced-binary-tree'],
      goal: '60 minutes, interview conditions, loud thinking.',
    },
    {
      day: 74,
      title: 'Full mock II',
      topicSlugs: ['sliding-window', 'heap'],
      problemIds: ['longest-repeating-character-replacement', 'k-closest-points-to-origin'],
      goal: '60 minutes: counters plus bounded heaps.',
    },
    {
      day: 75,
      title: 'Full mock III',
      topicSlugs: ['dynamic-programming-2d', 'advanced-graphs'],
      problemIds: ['edit-distance', 'course-schedule'],
      goal: '90 minutes: hard DP plus directed cycles.',
    },
    {
      day: 76,
      title: 'Full mock IV',
      topicSlugs: ['backtracking', 'trie'],
      problemIds: ['n-queens', 'implement-trie-prefix-tree'],
      goal: '90 minutes: constraint sets plus prefix maps.',
    },
    {
      day: 77,
      title: 'Revision: mock patterns',
      topicSlugs: ['two-pointers', 'hash-table'],
      problemIds: ['two-sum-ii-input-array-is-sorted', 'subarray-sum-equals-k'],
      goal: 'Extract reusable templates from four mocks.',
    },
    {
      day: 78,
      title: 'Behavioral + easy warmup',
      topicSlugs: ['problem-solving-framework', 'array'],
      problemIds: ['contains-duplicate', 'move-zeroes'],
      goal: 'Narrate one project deeply; warm up hands.',
    },
    {
      day: 79,
      title: 'Final ordered maps',
      topicSlugs: ['treemap-navigablemap', 'binary-search-tree'],
      problemIds: ['kth-smallest-element-in-a-bst', 'hand-of-straights'],
      goal: 'Order statistics and straight-counting maps.',
    },
    {
      day: 80,
      title: 'Final graphs pass',
      topicSlugs: ['weighted-graph', 'union-find'],
      problemIds: ['cheapest-flights-within-k-stops', 'number-of-connected-components-in-an-undirected-graph'],
      goal: 'Bounded relaxations and component counting.',
    },
    {
      day: 81,
      title: 'Final DP pass',
      topicSlugs: ['dynamic-programming-2d', 'knapsack'],
      problemIds: ['longest-common-subsequence', 'partition-equal-subset-sum'],
      goal: 'Diagonal matches and half-sum reductions.',
    },
    {
      day: 82,
      title: 'Final techniques pass',
      topicSlugs: ['monotonic-stack-queue', 'interval-problems'],
      problemIds: ['daily-temperatures', 'merge-intervals'],
      goal: 'Candidate stacks and sweep merges at speed.',
    },
    {
      day: 83,
      title: 'Dress rehearsal',
      topicSlugs: ['array', 'binary-tree'],
      problemIds: ['3sum', 'binary-tree-right-side-view'],
      goal: 'Full interview simulation with a peer or rubber duck.',
    },
    {
      day: 84,
      title: 'Revision: final review',
      topicSlugs: ['big-o-notation', 'collections-framework'],
      problemIds: ['two-sum', 'valid-parentheses'],
      goal: 'Complexity recitation and framework-map navigation.',
    },
    {
      day: 85,
      title: 'Capstone: strings',
      topicSlugs: ['string', 'dynamic-programming-1d'],
      problemIds: ['longest-palindromic-substring', 'decode-ways'],
      goal: 'Centers and decodings under exam pressure.',
    },
    {
      day: 86,
      title: 'Capstone: graphs',
      topicSlugs: ['bfs', 'dijkstra'],
      problemIds: ['rotting-oranges', 'swimming-in-rising-water'],
      goal: 'Multi-source waves and bottleneck paths.',
    },
    {
      day: 87,
      title: 'Capstone: DP',
      topicSlugs: ['dynamic-programming-2d', 'knapsack'],
      problemIds: ['regular-expression-matching', 'ones-and-zeroes'],
      goal: 'Star branches and two-capacity tables.',
    },
    {
      day: 88,
      title: 'Capstone: structures',
      topicSlugs: ['stack', 'singly-linked-list'],
      problemIds: ['car-fleet', 'merge-k-sorted-lists'],
      goal: 'Fleet stacks and heap merges to close structures.',
    },
    {
      day: 89,
      title: 'Capstone: mixed hard',
      topicSlugs: ['segment-tree', 'binary-search'],
      problemIds: ['median-of-two-sorted-arrays', 'minimum-interval-to-include-each-query'],
      goal: 'Two hards, full narration, no surrender.',
    },
    {
      day: 90,
      title: 'Graduation',
      topicSlugs: ['problem-solving-framework'],
      problemIds: ['two-sum', 'climbing-stairs'],
      goal: 'Re-run day one and day 33 favorites; compare the engineer you are now.',
    },
  ],
};
