import type { Sheet } from '../../types/content.ts';

/** 30-day fundamentals sprint: arrays through trees, ~2 topics + 2-3 problems a day. */
export const s4j30DaysChallenge: Sheet = {
  slug: 's4j-30-days-challenge',
  title: 'S4J 30-Day Challenge',
  description:
    'One focused month from Big-O basics to trees and heaps. Every day pairs about two topics with two or three hand-picked LeetCode problems, ending with mixed mocks and a capstone.',
  days: [
    {
      day: 1,
      title: 'How to think about algorithms',
      topicSlugs: ['big-o-notation', 'problem-solving-framework'],
      problemIds: ['two-sum', 'contains-duplicate'],
      goal: 'Explain Big-O and walk a full UNDERSTAND → TEST loop on two easy array problems.',
    },
    {
      day: 2,
      title: 'Arrays and dynamic growth',
      topicSlugs: ['array', 'dynamic-array'],
      problemIds: ['best-time-to-buy-and-sell-stock', 'move-zeroes'],
      goal: 'Index confidently and explain when a plain array beats an ArrayList.',
    },
    {
      day: 3,
      title: 'Searching, linear then binary',
      topicSlugs: ['linear-search', 'binary-search'],
      problemIds: ['binary-search', 'search-insert-position'],
      goal: 'Code both searches blind and state the sorted-input requirement.',
    },
    {
      day: 4,
      title: 'Strings and value semantics',
      topicSlugs: ['string', 'pass-by-value-java'],
      problemIds: ['valid-anagram', 'valid-palindrome'],
      goal: 'Manipulate strings without the == trap and predict what methods can mutate.',
    },
    {
      day: 5,
      title: 'Memory and linked lists',
      topicSlugs: ['memory-stack-vs-heap', 'singly-linked-list'],
      problemIds: ['reverse-linked-list', 'middle-of-the-linked-list'],
      goal: 'Draw stack vs heap for a list reversal and reverse any list in place.',
    },
    {
      day: 6,
      title: 'Stacks and queues',
      topicSlugs: ['stack', 'queue-deque'],
      problemIds: ['valid-parentheses', 'implement-queue-using-stacks'],
      goal: 'Match LIFO vs FIFO to problems and implement a queue from two stacks.',
    },
    {
      day: 7,
      title: 'Amortized cost and hashing',
      topicSlugs: ['amortized-analysis', 'hash-table'],
      problemIds: ['group-anagrams', 'design-hashmap'],
      goal: 'Argue ArrayList append is O(1) amortized and design a tiny hash map.',
    },
    {
      day: 8,
      title: 'Equality and sets',
      topicSlugs: ['equals-hashcode-contract', 'hash-set'],
      problemIds: ['happy-number', 'intersection-of-two-arrays'],
      goal: 'Write a correct equals/hashCode pair and dedupe with a set.',
    },
    {
      day: 9,
      title: 'Prefix sums and two pointers',
      topicSlugs: ['prefix-sum', 'two-pointers'],
      problemIds: ['subarray-sum-equals-k', 'two-sum-ii-input-array-is-sorted'],
      goal: 'Answer range sums in O(1) and converge pointers on sorted input.',
    },
    {
      day: 10,
      title: 'Sliding windows',
      topicSlugs: ['sliding-window'],
      problemIds: ['longest-substring-without-repeating-characters', 'permutation-in-string'],
      goal: 'Maintain a valid window with expand/shrink and track the best.',
    },
    {
      day: 11,
      title: 'Quadratic sorts, part 1',
      topicSlugs: ['bubble-sort', 'selection-sort'],
      problemIds: ['sort-colors', 'height-checker'],
      goal: 'Trace both sorts by hand and name when each is (un)acceptable.',
    },
    {
      day: 12,
      title: 'Quadratic sorts, part 2',
      topicSlugs: ['insertion-sort', 'counting-sort'],
      problemIds: ['h-index', 'contains-duplicate'],
      goal: 'Shift instead of swap, and count instead of compare for small ranges.',
    },
    {
      day: 13,
      title: 'Divide-and-conquer sorts',
      topicSlugs: ['merge-sort', 'quick-sort'],
      problemIds: ['merge-intervals', 'kth-largest-element-in-an-array'],
      goal: 'Partition around a pivot and merge sorted runs; contrast stability.',
    },
    {
      day: 14,
      title: 'Trees and recursion',
      topicSlugs: ['binary-tree', 'recursion-call-stack'],
      problemIds: ['maximum-depth-of-binary-tree', 'invert-binary-tree'],
      goal: 'Write the three traversals and predict max call-stack depth.',
    },
    {
      day: 15,
      title: 'Ordering and BSTs',
      topicSlugs: ['binary-search-tree', 'comparable-vs-comparator'],
      problemIds: ['validate-binary-search-tree', 'lowest-common-ancestor-of-a-binary-search-tree'],
      goal: 'Validate BST order with bounds and sort with custom comparators.',
    },
    {
      day: 16,
      title: 'Heaps and collections',
      topicSlugs: ['heap', 'collections-framework-map'],
      problemIds: ['last-stone-weight', 'top-k-frequent-elements'],
      goal: 'Run a size-k heap and pick the right java.util class per task.',
    },
    {
      day: 17,
      title: 'Tries and recurrence thinking',
      topicSlugs: ['trie', 'recursion-tree'],
      problemIds: ['implement-trie-prefix-tree', 'fibonacci-number'],
      goal: 'Share prefixes in a trie and count calls in a recursion tree.',
    },
    {
      day: 18,
      title: 'Two-speed pointers and doubly lists',
      topicSlugs: ['fast-slow-pointers', 'doubly-linked-list'],
      problemIds: ['linked-list-cycle', 'design-linked-list'],
      goal: 'Detect cycles with tortoise-and-hare and splice doubly lists both ways.',
    },
    {
      day: 19,
      title: 'Divide, backtrack, combine',
      topicSlugs: ['divide-and-conquer', 'backtracking'],
      problemIds: ['maximum-subarray', 'subsets'],
      goal: 'Split problems in half and explore decision trees with undo.',
    },
    {
      day: 20,
      title: 'Greedy choices and bits',
      topicSlugs: ['greedy', 'bit-manipulation'],
      problemIds: ['jump-game', 'single-number'],
      goal: 'Take provably-safe greedy steps and cancel pairs with XOR.',
    },
    {
      day: 21,
      title: 'Intervals and monotonic stacks',
      topicSlugs: ['interval-problems', 'monotonic-stack-queue'],
      problemIds: ['insert-interval', 'daily-temperatures'],
      goal: 'Sweep sorted intervals and keep candidates monotonic.',
    },
    {
      day: 22,
      title: 'Revision: arrays and strings',
      topicSlugs: ['array', 'string'],
      problemIds: ['product-of-array-except-self', 'longest-consecutive-sequence'],
      goal: 'Re-solve two mediums from week one without notes, under time.',
    },
    {
      day: 23,
      title: 'Revision: hashing and trees',
      topicSlugs: ['hash-table', 'binary-tree'],
      problemIds: ['top-k-frequent-elements', 'diameter-of-binary-tree'],
      goal: 'Explain every hash collision choice and trace a full traversal set.',
    },
    {
      day: 24,
      title: 'Revision: pointers and windows',
      topicSlugs: ['two-pointers', 'sliding-window'],
      problemIds: ['container-with-most-water', 'minimum-window-substring'],
      goal: 'Attempt one hard window problem; partial progress with clean code counts.',
    },
    {
      day: 25,
      title: 'Revision: sorting',
      topicSlugs: ['bubble-sort', 'quick-sort'],
      problemIds: ['squares-of-a-sorted-array', 'sort-an-array'],
      goal: 'Sort fluently and defend your algorithm choice per input shape.',
    },
    {
      day: 26,
      title: 'Revision: lists and stacks',
      topicSlugs: ['singly-linked-list', 'stack'],
      problemIds: ['reorder-list', 'min-stack'],
      goal: 'Splice lists without losing references and design a min-tracking stack.',
    },
    {
      day: 27,
      title: 'Mock: arrays and hashing',
      topicSlugs: ['array', 'hash-table'],
      problemIds: ['two-sum', 'group-anagrams', 'best-time-to-buy-and-sell-stock'],
      goal: '45-minute timed mock: three easies, clean code, tested edge cases.',
    },
    {
      day: 28,
      title: 'Mock: trees',
      topicSlugs: ['binary-tree', 'binary-search-tree'],
      problemIds: ['balanced-binary-tree', 'validate-binary-search-tree'],
      goal: '45-minute timed mock on tree recursion and BST validation.',
    },
    {
      day: 29,
      title: 'Mock: techniques',
      topicSlugs: ['sliding-window', 'backtracking'],
      problemIds: ['longest-substring-without-repeating-characters', 'permutations'],
      goal: '45-minute timed mock: one window, one backtracking enumeration.',
    },
    {
      day: 30,
      title: 'Capstone: heaps and BSTs',
      topicSlugs: ['heap', 'binary-search-tree'],
      problemIds: ['kth-smallest-element-in-a-bst', 'last-stone-weight'],
      goal: 'Finish with order statistics: kth-smallest and heap simulation under time.',
    },
  ],
};
