import type { Sheet } from '../../types/content.ts';

/** 60-day mastery: fundamentals first, then algorithms, heaps, graphs, and intro DP. */
export const s4j60DaysMastery: Sheet = {
  slug: 's4j-60-days-mastery',
  title: 'S4J 60-Day Strive',
  description:
    'Two months from zero to confident: weeks 1–4 rebuild fundamentals with fresh problem sets, weeks 5–8 add sorting depth, heaps, graphs, and your first dynamic programming.',
  difficulty: 'Intermediate',
  days: [
    {
      day: 1,
      title: 'Complexity glasses on',
      topicSlugs: ['big-o-notation', 'problem-solving-framework'],
      problemIds: ['contains-duplicate', 'missing-number'],
      goal: 'Rank any loop nest by growth and run the full solve loop twice.',
    },
    {
      day: 2,
      title: 'Array mechanics',
      topicSlugs: ['array', 'dynamic-array'],
      problemIds: ['move-zeroes', 'remove-duplicates-from-sorted-array'],
      goal: 'Shift, compact, and grow arrays by hand before trusting ArrayList.',
    },
    {
      day: 3,
      title: 'Search ladder',
      topicSlugs: ['linear-search', 'binary-search'],
      problemIds: ['first-bad-version', 'search-insert-position'],
      goal: 'Treat binary search as lower-bound machinery, not just lookup.',
    },
    {
      day: 4,
      title: 'String craft',
      topicSlugs: ['string', 'pass-by-value-java'],
      problemIds: ['reverse-string', 'valid-palindrome'],
      goal: 'Two-pointer strings and a crisp mutate-vs-rebind explanation.',
    },
    {
      day: 5,
      title: 'Nodes and references',
      topicSlugs: ['memory-stack-vs-heap', 'singly-linked-list'],
      problemIds: ['merge-two-sorted-lists', 'remove-nth-node-from-end-of-list'],
      goal: 'Dummy heads and gap pointers for every list edit.',
    },
    {
      day: 6,
      title: 'LIFO vs FIFO',
      topicSlugs: ['stack', 'queue-deque'],
      problemIds: ['min-stack', 'number-of-recent-calls'],
      goal: 'Auxiliary stacks and queue-from-stacks without hesitation.',
    },
    {
      day: 7,
      title: 'Hashing week checkpoint',
      topicSlugs: ['amortized-analysis', 'hash-table'],
      problemIds: ['valid-anagram', 'design-hashmap'],
      goal: 'Explain a resize and ship a chained hash map from memory.',
    },
    {
      day: 8,
      title: 'Sets and contracts',
      topicSlugs: ['equals-hashcode-contract', 'hash-set'],
      problemIds: ['happy-number', 'intersection-of-two-arrays'],
      goal: 'Cycle detection by set and a bulletproof value type.',
    },
    {
      day: 9,
      title: 'Ranges and pairs',
      topicSlugs: ['prefix-sum', 'two-pointers'],
      problemIds: ['find-pivot-index', '3sum'],
      goal: 'Prefix subtractions and a sorted triple scan.',
    },
    {
      day: 10,
      title: 'Window discipline',
      topicSlugs: ['sliding-window'],
      problemIds: ['longest-repeating-character-replacement', 'best-time-to-buy-and-sell-stock'],
      goal: 'Flexible windows with a validity invariant you can state.',
    },
    {
      day: 11,
      title: 'Simple sorts',
      topicSlugs: ['bubble-sort', 'selection-sort'],
      problemIds: ['sort-colors', 'height-checker'],
      goal: 'Know exactly what each quadratic sort guarantees (and ruins).',
    },
    {
      day: 12,
      title: 'Insertion and counting',
      topicSlugs: ['insertion-sort', 'counting-sort'],
      problemIds: ['h-index', 'sort-an-array'],
      goal: 'Adaptive shifting and frequency-table sorting.',
    },
    {
      day: 13,
      title: 'Merge and quick',
      topicSlugs: ['merge-sort', 'quick-sort'],
      problemIds: ['merge-sorted-array', 'kth-largest-element-in-an-array'],
      goal: 'Stable merging vs in-place partitioning, with pivot defense.',
    },
    {
      day: 14,
      title: 'Tree walks',
      topicSlugs: ['binary-tree', 'recursion-call-stack'],
      problemIds: ['invert-binary-tree', 'maximum-depth-of-binary-tree'],
      goal: 'All four traversals recursive and iterative.',
    },
    {
      day: 15,
      title: 'Ordered trees',
      topicSlugs: ['binary-search-tree', 'comparable-vs-comparator'],
      problemIds: ['kth-smallest-element-in-a-bst', 'lowest-common-ancestor-of-a-binary-search-tree'],
      goal: 'Inorder counting and guided LCA walks.',
    },
    {
      day: 16,
      title: 'Priority in practice',
      topicSlugs: ['heap', 'collections-framework-map'],
      problemIds: ['kth-largest-element-in-an-array', 'top-k-frequent-elements'],
      goal: 'Size-k heaps and the right collection per job.',
    },
    {
      day: 17,
      title: 'Prefixes and recurrence',
      topicSlugs: ['trie', 'recursion-tree'],
      problemIds: ['design-add-and-search-words-data-structure', 'powx-n'],
      goal: 'Wildcard trie DFS and halving recurrences.',
    },
    {
      day: 18,
      title: 'Cycles and cursors',
      topicSlugs: ['fast-slow-pointers', 'doubly-linked-list'],
      problemIds: ['find-the-duplicate-number', 'design-browser-history'],
      goal: 'Values-as-pointers cycles plus two-ended list surgery.',
    },
    {
      day: 19,
      title: 'Split and enumerate',
      topicSlugs: ['divide-and-conquer', 'backtracking'],
      problemIds: ['search-a-2d-matrix', 'combination-sum'],
      goal: 'Flattened search spaces and reuse-branch DFS.',
    },
    {
      day: 20,
      title: 'Greed and bits',
      topicSlugs: ['greedy', 'bit-manipulation'],
      problemIds: ['gas-station', 'counting-bits'],
      goal: 'Restart-on-deficit arguments and lowbit DP.',
    },
    {
      day: 21,
      title: 'Sweeps and monotonicity',
      topicSlugs: ['interval-problems', 'monotonic-stack-queue'],
      problemIds: ['non-overlapping-intervals', 'daily-temperatures'],
      goal: 'Earliest-finish greed and next-greater scans.',
    },
    {
      day: 22,
      title: 'Consolidation: arrays',
      topicSlugs: ['array', 'dynamic-array'],
      problemIds: ['product-of-array-except-self', 'longest-consecutive-sequence'],
      goal: 'Two mediums, no notes, clean edge-case handling.',
    },
    {
      day: 23,
      title: 'Consolidation: hashing',
      topicSlugs: ['hash-table', 'hash-set'],
      problemIds: ['group-anagrams', 'subarray-sum-equals-k'],
      goal: 'Key design (sorted vs frequency vs prefix) on sight.',
    },
    {
      day: 24,
      title: 'Consolidation: trees',
      topicSlugs: ['binary-tree', 'binary-search-tree'],
      problemIds: ['diameter-of-binary-tree', 'validate-binary-search-tree'],
      goal: 'Height-returning recursion and bounds-checked validation.',
    },
    {
      day: 25,
      title: 'Consolidation: techniques',
      topicSlugs: ['two-pointers', 'sliding-window'],
      problemIds: ['trapping-rain-water', 'minimum-window-substring'],
      goal: 'Two hards attempted with structured partial solutions.',
    },
    {
      day: 26,
      title: 'Consolidation: structures',
      topicSlugs: ['stack', 'queue-deque'],
      problemIds: ['evaluate-reverse-polish-notation', 'implement-stack-using-queues'],
      goal: 'Postfix evaluation and queue-rotated stacks.',
    },
    {
      day: 27,
      title: 'Mock: fundamentals',
      topicSlugs: ['array', 'string'],
      problemIds: ['two-sum', 'valid-anagram', 'best-time-to-buy-and-sell-stock'],
      goal: 'Timed trio: read, plan aloud, code, test.',
    },
    {
      day: 28,
      title: 'Mock: structures',
      topicSlugs: ['singly-linked-list', 'binary-tree'],
      problemIds: ['reverse-linked-list', 'same-tree'],
      goal: 'Timed pair with pointer-drawing before coding.',
    },
    {
      day: 29,
      title: 'Mock: techniques',
      topicSlugs: ['binary-search', 'sliding-window'],
      problemIds: ['search-in-rotated-sorted-array', 'longest-substring-without-repeating-characters'],
      goal: 'Rotated decay analysis plus a window invariant, timed.',
    },
    {
      day: 30,
      title: 'Midpoint review',
      topicSlugs: ['problem-solving-framework', 'big-o-notation'],
      problemIds: ['contains-duplicate', 'valid-parentheses'],
      goal: 'Audit weak spots; list five patterns to drill in month two.',
    },
    {
      day: 31,
      title: 'Heap sort and heaps',
      topicSlugs: ['heap-sort', 'heap'],
      problemIds: ['sort-an-array', 'find-median-from-data-stream'],
      goal: 'Bottom-up heapify and a two-heap median, both from memory.',
    },
    {
      day: 32,
      title: 'Backtracking depth',
      topicSlugs: ['backtracking', 'recursion-tree'],
      problemIds: ['permutations', 'subsets-ii'],
      goal: 'Used-sets vs index-starts, with duplicate skipping.',
    },
    {
      day: 33,
      title: 'Graphs first steps',
      topicSlugs: ['graph-representations', 'bfs'],
      problemIds: ['number-of-islands', 'binary-tree-level-order-traversal'],
      goal: 'Adjacency of choice plus wave-order traversal.',
    },
    {
      day: 34,
      title: 'DFS and union-find',
      topicSlugs: ['dfs', 'union-find'],
      problemIds: ['max-area-of-island', 'number-of-provinces'],
      goal: 'Flood fills and union-all-edges provinces.',
    },
    {
      day: 35,
      title: 'Weighted routes',
      topicSlugs: ['weighted-graph', 'dijkstra'],
      problemIds: ['network-delay-time', 'cheapest-flights-within-k-stops'],
      goal: 'Heap Dijkstra with stale-entry skips; k-stop limits via rounds.',
    },
    {
      day: 36,
      title: 'Negative edges and order',
      topicSlugs: ['bellman-ford', 'topological-sort'],
      problemIds: ['course-schedule', 'course-schedule-ii'],
      goal: 'Relax-everything rounds and Kahn ordering with cycle verdict.',
    },
    {
      day: 37,
      title: 'Cycles and spanning trees',
      topicSlugs: ['union-find-cycle-detection', 'kruskal'],
      problemIds: ['redundant-connection', 'min-cost-to-connect-all-points'],
      goal: 'First-cycle edge plus sort-and-union MST.',
    },
    {
      day: 38,
      title: 'Growing trees and ranges',
      topicSlugs: ['prim', 'segment-tree'],
      problemIds: ['range-sum-query-mutable', 'range-sum-query-immutable'],
      goal: 'Frontier-grown MSTs and interval-sum trees with updates.',
    },
    {
      day: 39,
      title: 'Fenwick and 1D DP',
      topicSlugs: ['fenwick-tree', 'dynamic-programming-1d'],
      problemIds: ['count-of-smaller-numbers-after-self', 'house-robber'],
      goal: 'Lowbit walks and skip-or-take states.',
    },
    {
      day: 40,
      title: 'DP grids and knapsacks',
      topicSlugs: ['dynamic-programming-2d', 'knapsack'],
      problemIds: ['unique-paths', 'partition-equal-subset-sum'],
      goal: 'Grid combines and half-sum subset reduction.',
    },
    {
      day: 41,
      title: 'Advanced graphs tour',
      topicSlugs: ['advanced-graphs'],
      problemIds: ['is-graph-bipartite', 'find-eventual-safe-states'],
      goal: 'Two-coloring and reverse-trim safety analysis.',
    },
    {
      day: 42,
      title: 'Strings under pressure',
      topicSlugs: ['string', 'sliding-window'],
      problemIds: ['minimum-window-substring', 'longest-repeating-character-replacement'],
      goal: 'Two hard windows with explicit validity counters.',
    },
    {
      day: 43,
      title: 'Trees under pressure',
      topicSlugs: ['binary-tree', 'binary-search-tree'],
      problemIds: ['binary-tree-maximum-path-sum', 'construct-binary-tree-from-preorder-and-inorder-traversal'],
      goal: 'Gain-or-drop paths and root-split reconstruction.',
    },
    {
      day: 44,
      title: 'Heaps under pressure',
      topicSlugs: ['heap', 'heap-sort'],
      problemIds: ['task-scheduler', 'k-closest-points-to-origin'],
      goal: 'Cooldown counting and bounded max-heaps.',
    },
    {
      day: 45,
      title: 'Graphs under pressure',
      topicSlugs: ['bfs', 'dfs'],
      problemIds: ['word-ladder', 'clone-graph'],
      goal: 'Implicit graphs and copy-maps, both directions of search.',
    },
    {
      day: 46,
      title: 'DP under pressure',
      topicSlugs: ['dynamic-programming-1d', 'dynamic-programming-2d'],
      problemIds: ['coin-change', 'longest-common-subsequence'],
      goal: 'Min-over-coins and diagonal-match tables.',
    },
    {
      day: 47,
      title: 'Backtracking under pressure',
      topicSlugs: ['backtracking', 'trie'],
      problemIds: ['word-search-ii', 'n-queens'],
      goal: 'Trie-pruned boards and column-diagonal sets.',
    },
    {
      day: 48,
      title: 'Intervals and greed',
      topicSlugs: ['interval-problems', 'greedy'],
      problemIds: ['merge-intervals', 'jump-game-ii'],
      goal: 'Sweep merges and jump-on-exhaustion, timed.',
    },
    {
      day: 49,
      title: 'Bits and math',
      topicSlugs: ['bit-manipulation', 'comparable-vs-comparator'],
      problemIds: ['sum-of-two-integers', 'reverse-integer'],
      goal: 'Carry loops and overflow-safe reversal.',
    },
    {
      day: 50,
      title: 'Matrices',
      topicSlugs: ['graph-representations', 'binary-search'],
      problemIds: ['rotate-image', 'spiral-matrix'],
      goal: 'In-place transforms with layer discipline.',
    },
    {
      day: 51,
      title: 'Mock: graphs',
      topicSlugs: ['bfs', 'union-find'],
      problemIds: ['number-of-islands', 'redundant-connection', 'rotting-oranges'],
      goal: '60-minute trio: flood, cycle, multi-source.',
    },
    {
      day: 52,
      title: 'Mock: DP',
      topicSlugs: ['dynamic-programming-1d', 'knapsack'],
      problemIds: ['house-robber', 'coin-change', 'target-sum'],
      goal: '60-minute trio: states, transitions, and subset transforms.',
    },
    {
      day: 53,
      title: 'Mock: trees and heaps',
      topicSlugs: ['binary-search-tree', 'heap'],
      problemIds: ['validate-binary-search-tree', 'kth-largest-element-in-an-array', 'top-k-frequent-elements'],
      goal: '60-minute trio with complexity narration throughout.',
    },
    {
      day: 54,
      title: 'Weak-spot surgery',
      topicSlugs: ['problem-solving-framework', 'big-o-notation'],
      problemIds: ['3sum', 'container-with-most-water'],
      goal: 'Re-attack logged failures with fresh eyes and a timer.',
    },
    {
      day: 55,
      title: 'Speed round: easies',
      topicSlugs: ['array', 'string'],
      problemIds: ['two-sum', 'valid-palindrome', 'best-time-to-buy-and-sell-stock'],
      goal: 'Three easies in 30 minutes, zero syntax stumbles.',
    },
    {
      day: 56,
      title: 'Speed round: mediums',
      topicSlugs: ['hash-table', 'two-pointers'],
      problemIds: ['group-anagrams', '3sum'],
      goal: 'Two mediums in 45 minutes with tested edge cases.',
    },
    {
      day: 57,
      title: 'System thinking',
      topicSlugs: ['collections-framework-map', 'hash-table'],
      problemIds: ['design-twitter', 'lru-cache'],
      goal: 'Design-flavored mediums: feeds, caches, and API tradeoffs.',
    },
    {
      day: 58,
      title: 'Hard day',
      topicSlugs: ['binary-tree', 'sliding-window'],
      problemIds: ['serialize-and-deserialize-binary-tree', 'sliding-window-maximum'],
      goal: 'Attempt two hards; structured partial credit beats flailing.',
    },
    {
      day: 59,
      title: 'Full mock',
      topicSlugs: ['dynamic-programming-2d', 'advanced-graphs'],
      problemIds: ['edit-distance', 'course-schedule', 'coin-change'],
      goal: '90-minute mock across DP and graphs, interview conditions.',
    },
    {
      day: 60,
      title: 'Graduation audit',
      topicSlugs: ['problem-solving-framework'],
      problemIds: ['two-sum', 'valid-parentheses'],
      goal: 'Re-run day-one problems; compare speed, clarity, and testing rigor.',
    },
  ],
};
