import { lazy } from 'react';
import type { ComponentType } from 'react';

/** A topic visualization: owns its own steps + VizPlayer, takes no props. */
export type VizComponent = ComponentType;

/**
 * Maps Topic.vizId → visualization component.
 * Each viz is lazy-loaded per route so topic pages only download
 * the animation they actually render.
 * TopicPage renders the match (inside Suspense), or a "Coming soon" box when missing.
 */
export const vizRegistry: Record<string, VizComponent> = {
  'array-ops': lazy(() => import('./ds/ArrayViz.tsx')),
  'dynamic-array-growth': lazy(() => import('./ds/DynamicArrayViz.tsx')),
  'string-builder': lazy(() => import('./ds/StringViz.tsx')),
  'sll-ops': lazy(() => import('./ds/SinglyLinkedListViz.tsx')),
  'dll-ops': lazy(() => import('./ds/DoublyLinkedListViz.tsx')),
  'stack-push-pop': lazy(() => import('./ds/StackViz.tsx')),
  'queue-deque-ops': lazy(() => import('./ds/QueueViz.tsx')),
  'hash-collision': lazy(() => import('./ds/HashViz.tsx')),
  'hash-set-ops': lazy(() => import('./ds/HashSetViz.tsx')),
  'binary-tree-traversals': lazy(() => import('./ds/BinaryTreeViz.tsx')),
  'bst-ops': lazy(() => import('./ds/BstViz.tsx')),
  'heap-ops': lazy(() => import('./ds/HeapViz.tsx')),
  'trie-ops': lazy(() => import('./ds/TrieViz.tsx')),
  'segment-tree-query': lazy(() => import('./ds/SegmentTreeViz.tsx')),
  'fenwick-ops': lazy(() => import('./ds/FenwickViz.tsx')),
  'union-find-ops': lazy(() => import('./ds/UnionFindViz.tsx')),
  'graph-representations': lazy(() => import('./ds/GraphRepViz.tsx')),
  'dijkstra-steps': lazy(() => import('./ds/DijkstraViz.tsx')),
  'advanced-graphs-tour': lazy(() => import('./ds/AdvancedGraphsViz.tsx')),
  'circular-list-ops': lazy(() => import('./ds/CircularListViz.tsx')),
  'circular-queue-ops': lazy(() => import('./ds/CircularQueueViz.tsx')),
  'matrix-ops': lazy(() => import('./ds/MatrixViz.tsx')),
  'skip-list-ops': lazy(() => import('./ds/SkipListViz.tsx')),
  'sparse-table-ops': lazy(() => import('./ds/SparseTableViz.tsx')),
  'bitset-ops': lazy(() => import('./ds/BitsetViz.tsx')),
  'avl-ops': lazy(() => import('./ds/AvlViz.tsx')),
  'monotonic-ops': lazy(() => import('./ds/MonotonicViz.tsx')),
  'sqrt-decomp-ops': lazy(() => import('./ds/SqrtDecompViz.tsx')),
  'minmax-heap-ops': lazy(() => import('./ds/MinMaxHeapViz.tsx')),
  'lru-cache-ops': lazy(() => import('./ds/LruCacheViz.tsx')),
  'suffix-array-ops': lazy(() => import('./ds/SuffixArrayViz.tsx')),
  'redblack-ops': lazy(() => import('./ds/RedBlackViz.tsx')),
  'btree-ops': lazy(() => import('./ds/BTreeViz.tsx')),
  'bloom-filter-ops': lazy(() => import('./ds/BloomFilterViz.tsx')),
  'collections-framework-map': lazy(() => import('./ds/FrameworkMapViz.tsx')),
  'arraylist-growth': lazy(() => import('./ds/ArrayListGrowthViz.tsx')),
  'failfast-modcount': lazy(() => import('./ds/FailFastViz.tsx')),
  'hashmap-buckets': lazy(() => import('./ds/HashMapBucketsViz.tsx')),
  'linkedhashmap-access': lazy(() => import('./ds/LinkedHashMapAccessViz.tsx')),
  'treemap-rotations': lazy(() => import('./ds/TreeMapRotationsViz.tsx')),
  'collections-sort-search': lazy(() => import('./ds/CollectionsSortSearchViz.tsx')),
  'arrays-fill-copy': lazy(() => import('./ds/ArraysFillCopyViz.tsx')),
  'immutable-snapshot': lazy(() => import('./ds/ImmutableSnapshotViz.tsx')),
  'streams-pipeline': lazy(() => import('./ds/StreamsPipelineViz.tsx')),
  'race-demo': lazy(() => import('./ds/RaceDemoViz.tsx')),
  'chm-segments': lazy(() => import('./ds/ChmSegmentsViz.tsx')),
  'cow-snapshot': lazy(() => import('./ds/CowSnapshotViz.tsx')),
  'cas-queue': lazy(() => import('./ds/CasQueueViz.tsx')),
  'pc-bounded': lazy(() => import('./ds/ProducerConsumerBoundedViz.tsx')),
  'linear-search-steps': lazy(() => import('./algo/LinearSearchViz.tsx')),
  'binary-search-steps': lazy(() => import('./algo/BinarySearchViz.tsx')),
  'bubble-sort-steps': lazy(() => import('./algo/BubbleSortViz.tsx')),
  'selection-sort-steps': lazy(() => import('./algo/SelectionSortViz.tsx')),
  'insertion-sort-steps': lazy(() => import('./algo/InsertionSortViz.tsx')),
  'merge-sort-steps': lazy(() => import('./algo/MergeSortViz.tsx')),
  'quick-sort-steps': lazy(() => import('./algo/QuickSortViz.tsx')),
  'heap-sort-steps': lazy(() => import('./algo/HeapSortViz.tsx')),
  'counting-sort-steps': lazy(() => import('./algo/CountingSortViz.tsx')),
  'two-pointers-steps': lazy(() => import('./algo/TwoPointersViz.tsx')),
  'sliding-window-steps': lazy(() => import('./algo/SlidingWindowViz.tsx')),
  'prefix-sum-steps': lazy(() => import('./algo/PrefixSumViz.tsx')),
  'fast-slow-steps': lazy(() => import('./algo/FastSlowViz.tsx')),
  'recursion-tree-steps': lazy(() => import('./algo/RecursionTreeViz.tsx')),
  'backtracking-steps': lazy(() => import('./algo/BacktrackingViz.tsx')),
  'divide-and-conquer-steps': lazy(() => import('./algo/DivideConquerViz.tsx')),
  'greedy-steps': lazy(() => import('./algo/GreedyViz.tsx')),
  'bfs-steps': lazy(() => import('./algo/BfsViz.tsx')),
  'dfs-steps': lazy(() => import('./algo/DfsViz.tsx')),
  'topological-sort-steps': lazy(() => import('./algo/TopoSortViz.tsx')),
  'dijkstra-algo-steps': lazy(() => import('./algo/DijkstraViz.tsx')),
  'bellman-ford-steps': lazy(() => import('./algo/BellmanFordViz.tsx')),
  'union-find-cycle-steps': lazy(() => import('./algo/UnionFindCycleViz.tsx')),
  'kruskal-steps': lazy(() => import('./algo/KruskalViz.tsx')),
  'prim-steps': lazy(() => import('./algo/PrimViz.tsx')),
  'dp-1d-steps': lazy(() => import('./algo/Dp1dViz.tsx')),
  'dp-2d-steps': lazy(() => import('./algo/Dp2dViz.tsx')),
  'knapsack-steps': lazy(() => import('./algo/KnapsackViz.tsx')),
  'big-o-curves': lazy(() => import('./concepts/BigOCurvesViz.tsx')),
  'recursion-call-stack': lazy(() => import('./concepts/CallStackViz.tsx')),
  'bit-operations': lazy(() => import('./concepts/BitOpsViz.tsx')),
  'monotonic-stack-steps': lazy(() => import('./concepts/MonotonicStackViz.tsx')),
};

export function getViz(vizId: string): VizComponent | undefined {
  return vizRegistry[vizId];
}
